package com.osframework.modellibrary.reference.common;

/**
 * The FindLocation application module consists of the following
 * classes:
 * 1) FindLocationUI - Autogenerated by generator.GenerateApplications.getUISource()
 *    this class is based on one of the templates in com.osframework.appclient.templates
 *    see oshis.mdb ApplicationLibrary table for the selected option.  The generator
 *    uses the oshis.mdb ControlLibrary to determine which UI controls are coded but at
 *    runtime the Reference tables Application Controls group will only display the controls
 *    with the display code of FindLocation.  The FindLocationUI class is devoid of business logic
 *    although the templates do add public methods to give access to some of the UI controls
 *    for the purpose of adding custom components, setting layouts etc.  The FindLocationController
 *    instantiates this class.
 * 2) FindLocationBaseController - Autogenerated by generator.GenerateApplications.getBaseControllerSource()
 *    this class creates the UIControls from oshis.mdb ConrolLibrary with listeners to get/set values
 *    from/on the associated model - FindLocationModel.  FindLocationController extends this class to add
 *    custom listeners.
 * 3) FindLocationModel - Since there is no specific database table model associated with this funcitonality
 *    the FindLocationModel is used to store the search fields - MRN, Name etc.
 * 4) FindLocationController -   This class is generated once by generator.GenerateApplications.getControllerSource()
 *    but will never be overwritted again (unless deleted).  The controller will initialize the UI, Model, add any
 *    custom controls and listeners to produce the application workflow.  The controller is started by an application 
 *    class which implements IParent.setValue(Object o) and is expecting a PatientSearchModel as the parameter passed.
 *    Typically the setValue will then trigger the calling applications workflow to handle the found patient.  The object
 *    will be null if no patient was found/selected.
*/
public class FindLocationModel implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String locationName;

	public String getLocationName() {
		return locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}
		
}
