/*
     * The ReferenceGroup model is a domain object which stores the groups of related lookup table id
 * as gender, locations, applications etc.   The reference group id is used in the Reference table,
 * 
 * The ReferenceGroupDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by ReferenceGroupModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to ReferenceGroupModel.  The ReferenceGroupList is a collection
 * of ReferenceGroupModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.

    Copyright (C) 2006  Aron Lancout Smith

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

*/
package com.osframework.modellibrary.reference.common;
import java.util.Enumeration;
import java.util.GregorianCalendar;
import java.util.Hashtable;
import java.util.Vector;

import com.osframework.appclient.services.ReferenceServices;
import com.osframework.ejb.reference.common.IReferenceMap;
import com.osframework.ejb.reference.security.ISecurity;
import com.osframework.framework.exceptions.ExceptionInfo;
import com.osframework.framework.locale.AppFormats;
import com.osframework.framework.logging.Debug;
import com.osframework.framework.utility.CalendarUtility;
import com.osframework.modellibrary.common.Comparison;
import com.osframework.modellibrary.common.DbCalendar;
import com.osframework.modellibrary.common.IControlModel;
import com.osframework.modellibrary.common.ResultColumnList;
import com.osframework.modellibrary.reference.group.DatabaseDataTypeFramework;
import com.osframework.modellibrary.reference.group.SystemMessageFramework;

/**
 * The ReferenceGroup model is a domain object which stores the groups of related lookup table id
 * as gender, locations, applications etc.   The reference group id is used in the Reference table,
 * 
 * The ReferenceGroupDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by ReferenceGroupModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to ReferenceGroupModel.  The ReferenceGroupList is a collection
 * of ReferenceGroupModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.
*/
public class ReferenceGroupDataModel implements IControlModel, java.io.Serializable {

	static final long serialVersionUID = 1L;
	private int hashsize = 16;
	private Hashtable modifiedFields = new Hashtable(hashsize);
	private boolean referenceSet = false;


	/** Unique reference group identifier  */
	private int referenceGroupId = 0;

	/** Unique code for this reference group  */
	private String referenceGroup;

	/** Name for the group of reference codes  */
	private String display;

	/** Description of this group of reference codes  */
	private String description;

	/** Control users have over the reference  */
	private int modificationRefId = 324;

	private String modificationRefDisplay="";

	/** Reference category  */
	private int categoryRefId = 0;

	private String categoryRefDisplay="";

	/** Ignoring the sequence 0: Duplicate display codes 1: No duplicate display codes  */
	private int uniqueDisplayCodeInd = 1;

	/** Group is part of the core framework  */
	private int frameworkInd = 0;

	/** Date the record was created  */
	private DbCalendar createDt = DbCalendar.getDbCalendar();

	/** User that created this record  */
	private int createUserId = 0;

	private String createUserName="";

	/** Date the record was updated  */
	private DbCalendar updateDt = DbCalendar.getDbCalendar();

	/** Date the record was last updated  */
	private int updateUserId = 0;

	private String updateUserName="";

	/** Number of times this record has been updated  */
	private int updateCount = 0;

	/** Active indicator 1=Active 0=Inactive  */
	private int activeInd = 1;

	/** 0: Customer defined >0:   */
	private int systemAssignedVersionNbr = 5;

	/** Identifies database row as Reference or Record and System or User entered  */
	private int recordTypeRefId = 321;

	private String recordTypeRefDisplay="";


	/** 
	 * Unique reference group identifier
	 * 
	 */ 
	public int getReferenceGroupId() {
		return referenceGroupId;
	}

	/** 
	 * Unique reference group identifier
	 * 
	 */ 
	public void setReferenceGroupId(int referenceGroupId) {
		if (!Comparison.areEqual(this.referenceGroupId, referenceGroupId)) {
			this.referenceGroupId = referenceGroupId;
			setModified("referenceGroupId");
		};
	}

	/** 
	 * Unique code for this reference group
	 * 
	 */ 
	public String getReferenceGroup() {
		return referenceGroup;
	}

	/** 
	 * Unique code for this reference group
	 * 
	 */ 
	public void setReferenceGroup(String referenceGroup) {
		if (!Comparison.areEqual(this.referenceGroup, referenceGroup)) {
			this.referenceGroup = referenceGroup;
			setModified("referenceGroup");
		};
	}

	/** 
	 * Name for the group of reference codes
	 * 
	 */ 
	public String getDisplay() {
		return display;
	}

	/** 
	 * Name for the group of reference codes
	 * 
	 */ 
	public void setDisplay(String display) {
		if (!Comparison.areEqual(this.display, display)) {
			this.display = display;
			setModified("display");
		};
	}

	/** 
	 * Description of this group of reference codes
	 * 
	 */ 
	public String getDescription() {
		return description;
	}

	/** 
	 * Description of this group of reference codes
	 * 
	 */ 
	public void setDescription(String description) {
		if (!Comparison.areEqual(this.description, description)) {
			this.description = description;
			setModified("description");
		};
	}

	/** 
	 * Control users have over the reference
	 * 
	 */ 
	public int getModificationRefId() {
		return modificationRefId;
	}

	/** 
	 * Control users have over the reference
	 * 
	 * Required database field.
	 */ 
	public void setModificationRefId(int modificationRefId) {
		if (!Comparison.areEqual(this.modificationRefId, modificationRefId)) {
			this.modificationRefId = modificationRefId;
			setModified("modificationRefId");
		};
	}

	/** 
	 * Control users have over the reference
	 * 
	 */ 
	public String getModificationRefDisplay() {
		return modificationRefDisplay;
	}

	/** 
	 * Control users have over the reference
	 * 
	 */ 
	public void setModificationRefDisplay(String display) {
		this.modificationRefDisplay = display;
	}

	/** 
	 * Reference category
	 * 
	 */ 
	public int getCategoryRefId() {
		return categoryRefId;
	}

	/** 
	 * Reference category
	 * 
	 * Required database field.
	 */ 
	public void setCategoryRefId(int categoryRefId) {
		if (!Comparison.areEqual(this.categoryRefId, categoryRefId)) {
			this.categoryRefId = categoryRefId;
			setModified("categoryRefId");
		};
	}

	/** 
	 * Reference category
	 * 
	 */ 
	public String getCategoryRefDisplay() {
		return categoryRefDisplay;
	}

	/** 
	 * Reference category
	 * 
	 */ 
	public void setCategoryRefDisplay(String display) {
		this.categoryRefDisplay = display;
	}

	/** 
	 * Ignoring the sequence 0: Duplicate display codes 1: No duplicate display codes
	 * 
	 */ 
	public int getUniqueDisplayCodeInd() {
		return uniqueDisplayCodeInd;
	}

	/** 
	 * Ignoring the sequence 0: Duplicate display codes 1: No duplicate display codes
	 * 
	 * Required database field.
	 */ 
	public void setUniqueDisplayCodeInd(int uniqueDisplayCodeInd) {
		if (!Comparison.areEqual(this.uniqueDisplayCodeInd, uniqueDisplayCodeInd)) {
			this.uniqueDisplayCodeInd = uniqueDisplayCodeInd;
			setModified("uniqueDisplayCodeInd");
		};
	}

	/** 
	 * Ignoring the sequence 0: Duplicate display codes 1: No duplicate display codes
	 * 
	 */ 
	public boolean isUniqueDisplayCode() {
		return uniqueDisplayCodeInd == 1;
	}

	/** 
	 * Ignoring the sequence 0: Duplicate display codes 1: No duplicate display codes
	 * 
	 */ 
	public boolean isNotUniqueDisplayCode() {
		return uniqueDisplayCodeInd == 0;
	}

	/** 
	 * Ignoring the sequence 0: Duplicate display codes 1: No duplicate display codes
	 * 
	 */ 
	public void setUniqueDisplayCode() {
		this.setUniqueDisplayCodeInd(1);
	}

	public void setNotUniqueDisplayCode() {
		this.setUniqueDisplayCodeInd(0);
	}

	/** 
	 * Group is part of the core framework
	 * 
	 */ 
	public int getFrameworkInd() {
		return frameworkInd;
	}

	/** 
	 * Group is part of the core framework
	 * 
	 * Required database field.
	 */ 
	public void setFrameworkInd(int frameworkInd) {
		if (!Comparison.areEqual(this.frameworkInd, frameworkInd)) {
			this.frameworkInd = frameworkInd;
			setModified("frameworkInd");
		};
	}

	/** 
	 * Group is part of the core framework
	 * 
	 */ 
	public boolean isFramework() {
		return frameworkInd == 1;
	}

	/** 
	 * Group is part of the core framework
	 * 
	 */ 
	public boolean isNotFramework() {
		return frameworkInd == 0;
	}

	/** 
	 * Group is part of the core framework
	 * 
	 */ 
	public void setFramework() {
		this.setFrameworkInd(1);
	}

	public void setNotFramework() {
		this.setFrameworkInd(0);
	}

	/** 
	 * Date the record was created
	 * 
	 */ 
	public DbCalendar getCreateDt() {
		return createDt;
	}

	/** 
	 * Date the record was created
	 * 
	 */ 
	public void setCreateDt(GregorianCalendar createDt) {
		if (!Comparison.areEqual(this.createDt, createDt)) {
			this.createDt = new DbCalendar();
			if (createDt != null) {
				this.createDt.setTimeInMillis(createDt.getTimeInMillis());
			}
			setModified("createDt");
		};
	}

	/** 
	 * Date the record was created
	 * 
	 */ 
	public void setCreateDt(long milliseconds) {
		if (this.createDt==null) {
			this.createDt = new DbCalendar();
		}
		if (!Comparison.areEqual(this.createDt, createDt)) {
			this.createDt.setTimeInMillis(milliseconds);
			setModified("createDt");
		}

	}

	/** 
	 * User that created this record
	 * 
	 */ 
	public int getCreateUserId() {
		return createUserId;
	}

	/** 
	 * User that created this record
	 * 
	 * Required database field.
	 */ 
	public void setCreateUserId(int createUserId) {
		if (!Comparison.areEqual(this.createUserId, createUserId)) {
			this.createUserId = createUserId;
			setModified("createUserId");
		};
	}

	/** 
	 * User that created this record
	 * 
	 */ 
	public String getCreateUserName() {
		return createUserName;
	}

	/** 
	 * User that created this record
	 * 
	 */ 
	public void setCreateUserName(String userName) {
		this.createUserName = userName;
	}

	/** 
	 * Date the record was updated
	 * 
	 */ 
	public DbCalendar getUpdateDt() {
		return updateDt;
	}

	/** 
	 * Date the record was updated
	 * 
	 */ 
	public void setUpdateDt(GregorianCalendar updateDt) {
		if (!Comparison.areEqual(this.updateDt, updateDt)) {
			this.updateDt = new DbCalendar();
			if (updateDt != null) {
				this.updateDt.setTimeInMillis(updateDt.getTimeInMillis());
			}
			setModified("updateDt");
		};
	}

	/** 
	 * Date the record was updated
	 * 
	 */ 
	public void setUpdateDt(long milliseconds) {
		if (this.updateDt==null) {
			this.updateDt = new DbCalendar();
		}
		if (!Comparison.areEqual(this.updateDt, updateDt)) {
			this.updateDt.setTimeInMillis(milliseconds);
			setModified("updateDt");
		}

	}

	/** 
	 * Date the record was last updated
	 * 
	 */ 
	public int getUpdateUserId() {
		return updateUserId;
	}

	/** 
	 * Date the record was last updated
	 * 
	 * Required database field.
	 */ 
	public void setUpdateUserId(int updateUserId) {
		if (!Comparison.areEqual(this.updateUserId, updateUserId)) {
			this.updateUserId = updateUserId;
			setModified("updateUserId");
		};
	}

	/** 
	 * Date the record was last updated
	 * 
	 */ 
	public String getUpdateUserName() {
		return updateUserName;
	}

	/** 
	 * Date the record was last updated
	 * 
	 */ 
	public void setUpdateUserName(String userName) {
		this.updateUserName = userName;
	}

	/** 
	 * Number of times this record has been updated
	 * 
	 */ 
	public int getUpdateCount() {
		return updateCount;
	}

	/** 
	 * Number of times this record has been updated
	 * 
	 * Required database field.
	 */ 
	public void setUpdateCount(int updateCount) {
		if (!Comparison.areEqual(this.updateCount, updateCount)) {
			this.updateCount = updateCount;
			setModified("updateCount");
		};
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public int getActiveInd() {
		return activeInd;
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 * Required database field.
	 */ 
	public void setActiveInd(int activeInd) {
		if (!Comparison.areEqual(this.activeInd, activeInd)) {
			this.activeInd = activeInd;
			setModified("activeInd");
		};
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public boolean isActive() {
		return activeInd == 1;
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public boolean isNotActive() {
		return activeInd == 0;
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public void setActive() {
		this.setActiveInd(1);
	}

	public void setNotActive() {
		this.setActiveInd(0);
	}

	/** 
	 * 0: Customer defined >0: 
	 * 
	 */ 
	public int getSystemAssignedVersionNbr() {
		return systemAssignedVersionNbr;
	}

	/** 
	 * 0: Customer defined >0: 
	 * 
	 * Required database field.
	 */ 
	public void setSystemAssignedVersionNbr(int systemAssignedVersionNbr) {
		if (!Comparison.areEqual(this.systemAssignedVersionNbr, systemAssignedVersionNbr)) {
			this.systemAssignedVersionNbr = systemAssignedVersionNbr;
			setModified("systemAssignedVersionNbr");
		};
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 */ 
	public int getRecordTypeRefId() {
		return recordTypeRefId;
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 * Required database field.
	 */ 
	public void setRecordTypeRefId(int recordTypeRefId) {
		if (!Comparison.areEqual(this.recordTypeRefId, recordTypeRefId)) {
			this.recordTypeRefId = recordTypeRefId;
			setModified("recordTypeRefId");
		};
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 */ 
	public String getRecordTypeRefDisplay() {
		return recordTypeRefDisplay;
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 */ 
	public void setRecordTypeRefDisplay(String display) {
		this.recordTypeRefDisplay = display;
	}


public static ResultColumnList getResultColumnList() {
	ResultColumnList columns = new ResultColumnList();
		columns.addColumn("referenceGroupId", Integer.class);
		columns.addColumn("referenceGroup", String.class);
		columns.addColumn("display", String.class);
		columns.addColumn("description", String.class);
		columns.addColumn("modificationRefId", Integer.class);
		columns.addColumn("modificationRefDisplay", String.class);
		columns.addColumn("categoryRefId", Integer.class);
		columns.addColumn("categoryRefDisplay", String.class);
		columns.addColumn("uniqueDisplayCodeInd", Integer.class);
		columns.addColumn("frameworkInd", Integer.class);
		columns.addColumn("createDt", GregorianCalendar.class);
		columns.addColumn("createUserId", Integer.class);
		columns.addColumn("createUserName", String.class);
		columns.addColumn("updateDt", GregorianCalendar.class);
		columns.addColumn("updateUserId", Integer.class);
		columns.addColumn("updateUserName", String.class);
		columns.addColumn("updateCount", Integer.class);
		columns.addColumn("activeInd", Integer.class);
		columns.addColumn("systemAssignedVersionNbr", Integer.class);
		columns.addColumn("recordTypeRefId", Integer.class);
		columns.addColumn("recordTypeRefDisplay", String.class);
		return columns;
	}
		
	/** 
	 * Flags this field as being modified
	 */ 
	public void setReferenceDisplay(IReferenceMap reference, ISecurity security) {
		try {
			if (referenceSet) {
				return;
			}
		referenceSet = true;
			if (reference != null && this.modificationRefId > 0) setModificationRefDisplay(reference.getDisplay(this.modificationRefId));
			if (reference != null && this.categoryRefId > 0) setCategoryRefDisplay(reference.getDisplay(this.categoryRefId));
			if (security != null && this.createUserId > 0) setCreateUserName(security.getUser(this.createUserId).getDisplayName());
			if (security != null && this.updateUserId > 0) setUpdateUserName(security.getUser(this.updateUserId).getDisplayName());
			if (reference != null && this.recordTypeRefId > 0) setRecordTypeRefDisplay(reference.getDisplay(this.recordTypeRefId));
		} catch (Exception e) {
			Debug.LogException(this, e);
		}
	}		
	/** 
	 * Flags this field as being modified
	 */ 
	public void setModified(String fieldName) {
		if (!modifiedFields.containsKey(fieldName)) {
			modifiedFields.put(fieldName, "1");
		}
	}

	/** 
	 * Resets flagged fields so none are marked as modified
	 */ 
	public void resetModified() {
		modifiedFields = new Hashtable(hashsize);
	}

	public boolean hasModified() {
		return modifiedFields.size() > 0;
	}

	
		
	/** 
	 * Copys the values of all modified fields to object m
	 */ 
	public void copyModifiedTo(ReferenceGroupDataModel m) {
		Enumeration e1 = modifiedFields.keys();
		while (e1.hasMoreElements()) {
			String fieldName = (String) e1.nextElement();

			if (fieldName.compareTo("referenceGroupId")==0)
				m.setReferenceGroupId(this.getReferenceGroupId());
			else if (fieldName.compareTo("referenceGroup")==0)
				m.setReferenceGroup(this.getReferenceGroup());
			else if (fieldName.compareTo("display")==0)
				m.setDisplay(this.getDisplay());
			else if (fieldName.compareTo("description")==0)
				m.setDescription(this.getDescription());
			else if (fieldName.compareTo("modificationRefId")==0)
				m.setModificationRefId(this.getModificationRefId());
			else if (fieldName.compareTo("categoryRefId")==0)
				m.setCategoryRefId(this.getCategoryRefId());
			else if (fieldName.compareTo("uniqueDisplayCodeInd")==0)
				m.setUniqueDisplayCodeInd(this.getUniqueDisplayCodeInd());
			else if (fieldName.compareTo("frameworkInd")==0)
				m.setFrameworkInd(this.getFrameworkInd());
			else if (fieldName.compareTo("createDt")==0)
				m.setCreateDt(this.getCreateDt());
			else if (fieldName.compareTo("createUserId")==0)
				m.setCreateUserId(this.getCreateUserId());
			else if (fieldName.compareTo("updateDt")==0)
				m.setUpdateDt(this.getUpdateDt());
			else if (fieldName.compareTo("updateUserId")==0)
				m.setUpdateUserId(this.getUpdateUserId());
			else if (fieldName.compareTo("updateCount")==0)
				m.setUpdateCount(this.getUpdateCount());
			else if (fieldName.compareTo("activeInd")==0)
				m.setActiveInd(this.getActiveInd());
			else if (fieldName.compareTo("systemAssignedVersionNbr")==0)
				m.setSystemAssignedVersionNbr(this.getSystemAssignedVersionNbr());
			else if (fieldName.compareTo("recordTypeRefId")==0)
				m.setRecordTypeRefId(this.getRecordTypeRefId());
			else 		
				Debug.LogError(this, ExceptionInfo.invalidCopyModifiedField + " " + fieldName);
	}
}

	/**
	 * Update this object with the data from m
	 */
	public void updateWith (ReferenceGroupModel m) {

		this.setReferenceGroupId(m.getReferenceGroupId());
		this.setReferenceGroup(m.getReferenceGroup());
		this.setDisplay(m.getDisplay());
		this.setDescription(m.getDescription());
		this.setModificationRefId(m.getModificationRefId());
		this.setModificationRefDisplay(m.getModificationRefDisplay());
		this.setCategoryRefId(m.getCategoryRefId());
		this.setCategoryRefDisplay(m.getCategoryRefDisplay());
		this.setUniqueDisplayCodeInd(m.getUniqueDisplayCodeInd());
		this.setFrameworkInd(m.getFrameworkInd());
		this.setCreateDt(m.getCreateDt());
		this.setCreateUserId(m.getCreateUserId());
		this.setCreateUserName(m.getCreateUserName());
		this.setUpdateDt(m.getUpdateDt());
		this.setUpdateUserId(m.getUpdateUserId());
		this.setUpdateUserName(m.getUpdateUserName());
		this.setUpdateCount(m.getUpdateCount());
		this.setActiveInd(m.getActiveInd());
		this.setSystemAssignedVersionNbr(m.getSystemAssignedVersionNbr());
		this.setRecordTypeRefId(m.getRecordTypeRefId());
		this.setRecordTypeRefDisplay(m.getRecordTypeRefDisplay());
	}

	/**
	 * Compare the two objects
	 */
	public boolean isEqualTo (ReferenceGroupModel m) {

		if (!Comparison.areEqual(this.getReferenceGroupId(),  m.getReferenceGroupId())) return false;
		if (!Comparison.areEqual(this.getReferenceGroup(),  m.getReferenceGroup())) return false;
		if (!Comparison.areEqual(this.getDisplay(),  m.getDisplay())) return false;
		if (!Comparison.areEqual(this.getDescription(),  m.getDescription())) return false;
		if (!Comparison.areEqual(this.getModificationRefId(),  m.getModificationRefId())) return false;
		if (!Comparison.areEqual(this.getCategoryRefId(),  m.getCategoryRefId())) return false;
		if (!Comparison.areEqual(this.getUniqueDisplayCodeInd(),  m.getUniqueDisplayCodeInd())) return false;
		if (!Comparison.areEqual(this.getFrameworkInd(),  m.getFrameworkInd())) return false;
		if (!Comparison.areEqual(this.getCreateDt(),  m.getCreateDt())) return false;
		if (!Comparison.areEqual(this.getCreateUserId(),  m.getCreateUserId())) return false;
		if (!Comparison.areEqual(this.getUpdateCount(),  m.getUpdateCount())) return false;
		if (!Comparison.areEqual(this.getActiveInd(),  m.getActiveInd())) return false;
		if (!Comparison.areEqual(this.getSystemAssignedVersionNbr(),  m.getSystemAssignedVersionNbr())) return false;
		if (!Comparison.areEqual(this.getRecordTypeRefId(),  m.getRecordTypeRefId())) return false;
		return true;
	}
	/**
	 * Returns a list of all field names which are required and are null
	 */
	public Vector getMissingRequired () {

		Vector v = new Vector();
		return v;
	}
	public String toString() {
		try {
			StringBuffer sb = new StringBuffer(1024);
			sb.append("ReferenceGroupModel:\r\n");
			sb.append("reference_group_id:" + getReferenceGroupId());
			sb.append("\r\n");
			sb.append("reference_group:" + getReferenceGroup());
			sb.append("\r\n");
			sb.append("display:" + getDisplay());
			sb.append("\r\n");
			sb.append("description:" + getDescription());
			sb.append("\r\n");
			sb.append("modification_ref_id:" + getModificationRefId());
			sb.append("\r\n");
			sb.append("modification_ref_display:" + getModificationRefDisplay());
			sb.append("\r\n");
			sb.append("category_ref_id:" + getCategoryRefId());
			sb.append("\r\n");
			sb.append("category_ref_display:" + getCategoryRefDisplay());
			sb.append("\r\n");
			sb.append("unique_display_code_ind:" + getUniqueDisplayCodeInd());
			sb.append("\r\n");
			sb.append("framework_ind:" + getFrameworkInd());
			sb.append("\r\n");
			sb.append("create_dt:" + CalendarUtility.Format(getCreateDt(),AppFormats.getLongDateTimeFormat()));
			sb.append("\r\n");
			sb.append("create_user_id:" + getCreateUserId());
			sb.append("\r\n");
			sb.append("create_user_name:" + getCreateUserName());
			sb.append("\r\n");
			sb.append("update_dt:" + CalendarUtility.Format(getUpdateDt(),AppFormats.getLongDateTimeFormat()));
			sb.append("\r\n");
			sb.append("update_user_id:" + getUpdateUserId());
			sb.append("\r\n");
			sb.append("update_user_name:" + getUpdateUserName());
			sb.append("\r\n");
			sb.append("update_count:" + getUpdateCount());
			sb.append("\r\n");
			sb.append("active_ind:" + getActiveInd());
			sb.append("\r\n");
			sb.append("system_assigned_version_nbr:" + getSystemAssignedVersionNbr());
			sb.append("\r\n");
			sb.append("record_type_ref_id:" + getRecordTypeRefId());
			sb.append("\r\n");
			sb.append("record_type_ref_display:" + getRecordTypeRefDisplay());
			sb.append("\r\n");
			return sb.toString();
		} catch (Exception ex) {
			return "ReferenceGroupModel:"; 
		}
	}
	public void setModelColDataAt(Object o, int modelCol) {
			switch (modelCol) {
			case 520: setReferenceGroupId(((Integer) o).intValue()); break;
			case 521: setReferenceGroup((String) o); break;
			case 522: setDisplay((String) o); break;
			case 523: setDescription((String) o); break;
			case 524: setModificationRefId(((Integer) o).intValue()); break;
			case 525: setCategoryRefId(((Integer) o).intValue()); break;
			case 526: setUniqueDisplayCodeInd(((Integer) o).intValue()); break;
			case 527: setFrameworkInd(((Integer) o).intValue()); break;
			case 528: setCreateDt((GregorianCalendar) o); break;
			case 529: setCreateUserId(((Integer) o).intValue()); break;
			case 804: setCreateUserName((String) o); break;
			case 530: setUpdateDt((GregorianCalendar) o); break;
			case 531: setUpdateUserId(((Integer) o).intValue()); break;
			case 805: setUpdateUserName((String) o); break;
			case 532: setUpdateCount(((Integer) o).intValue()); break;
			case 533: setActiveInd(((Integer) o).intValue()); break;
			case 534: setSystemAssignedVersionNbr(((Integer) o).intValue()); break;
			case 535: setRecordTypeRefId(((Integer) o).intValue()); break;
			default: Debug.LogWarning(this, ReferenceServices.getMsg(SystemMessageFramework.SWITCHSTATEMENTFAILED) + " modelColRefId: " + modelCol);
	} 
}

	public Object getModelColDataAt(int modelCol) {
			if (modelCol == 520) return new Integer(referenceGroupId);
			if (modelCol == 521) return referenceGroup;
			if (modelCol == 522) return display;
			if (modelCol == 523) return description;
			if (modelCol == 524) return new Integer(modificationRefId);
			if (modelCol == 524) return modificationRefDisplay;
			if (modelCol == 525) return new Integer(categoryRefId);
			if (modelCol == 525) return categoryRefDisplay;
			if (modelCol == 526) return new Integer(uniqueDisplayCodeInd);
			if (modelCol == 527) return new Integer(frameworkInd);
			if (modelCol == 528) return createDt;
			if (modelCol == 529) return new Integer(createUserId);
			if (modelCol == 529) return createUserName;
			if (modelCol == 530) return updateDt;
			if (modelCol == 531) return new Integer(updateUserId);
			if (modelCol == 531) return updateUserName;
			if (modelCol == 532) return new Integer(updateCount);
			if (modelCol == 533) return new Integer(activeInd);
			if (modelCol == 534) return new Integer(systemAssignedVersionNbr);
			if (modelCol == 535) return new Integer(recordTypeRefId);
			if (modelCol == 535) return recordTypeRefDisplay;
		return null;
	}

	public int getModelColDatabaseDataType(int modelCol) {
			if (modelCol == 520) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 521) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 522) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 523) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 524) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 524) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 525) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 525) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 526) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 527) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 528) return DatabaseDataTypeFramework.DATE;
			if (modelCol == 529) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 529) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 530) return DatabaseDataTypeFramework.DATE;
			if (modelCol == 531) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 531) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 532) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 533) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 534) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 535) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 535) return DatabaseDataTypeFramework.STRING;
			return DatabaseDataTypeFramework.STRING;
	}

	public boolean isNew() {
		return getReferenceGroupId() == 0;
	}

	public Object getPrimaryValue() {
		return new Integer(getReferenceGroupId());
	}

	public Object getDataAt(int i) {
			if (i == 0) return new Integer(referenceGroupId);
			if (i == 1) return referenceGroup;
			if (i == 2) return display;
			if (i == 3) return description;
			if (i == 4) return new Integer(modificationRefId);
			if (i == 5) return modificationRefDisplay;
			if (i == 6) return new Integer(categoryRefId);
			if (i == 7) return categoryRefDisplay;
			if (i == 8) return new Integer(uniqueDisplayCodeInd);
			if (i == 9) return new Integer(frameworkInd);
			if (i == 10) return createDt;
			if (i == 11) return new Integer(createUserId);
			if (i == 12) return createUserName;
			if (i == 13) return updateDt;
			if (i == 14) return new Integer(updateUserId);
			if (i == 15) return updateUserName;
			if (i == 16) return new Integer(updateCount);
			if (i == 17) return new Integer(activeInd);
			if (i == 18) return new Integer(systemAssignedVersionNbr);
			if (i == 19) return new Integer(recordTypeRefId);
			if (i == 20) return recordTypeRefDisplay;
		return null;
	}

	public int getDatabaseDataType(int i) {
			if (i == 0) return DatabaseDataTypeFramework.INTEGER;
			if (i == 1) return DatabaseDataTypeFramework.STRING;
			if (i == 2) return DatabaseDataTypeFramework.STRING;
			if (i == 3) return DatabaseDataTypeFramework.STRING;
			if (i == 4) return DatabaseDataTypeFramework.INTEGER;
			if (i == 5) return DatabaseDataTypeFramework.STRING;
			if (i == 6) return DatabaseDataTypeFramework.INTEGER;
			if (i == 7) return DatabaseDataTypeFramework.STRING;
			if (i == 8) return DatabaseDataTypeFramework.INTEGER;
			if (i == 9) return DatabaseDataTypeFramework.INTEGER;
			if (i == 10) return DatabaseDataTypeFramework.DATE;
			if (i == 11) return DatabaseDataTypeFramework.INTEGER;
			if (i == 12) return DatabaseDataTypeFramework.STRING;
			if (i == 13) return DatabaseDataTypeFramework.DATE;
			if (i == 14) return DatabaseDataTypeFramework.INTEGER;
			if (i == 15) return DatabaseDataTypeFramework.STRING;
			if (i == 16) return DatabaseDataTypeFramework.INTEGER;
			if (i == 17) return DatabaseDataTypeFramework.INTEGER;
			if (i == 18) return DatabaseDataTypeFramework.INTEGER;
			if (i == 19) return DatabaseDataTypeFramework.INTEGER;
			if (i == 20) return DatabaseDataTypeFramework.STRING;
			return DatabaseDataTypeFramework.STRING;
	}

	public void setDataAt(Object o, int i) {
		switch(i) {
			case 0: setReferenceGroupId(((Integer) o).intValue()); break;
			case 1: setReferenceGroup((String) o); break;
			case 2: setDisplay((String) o); break;
			case 3: setDescription((String) o); break;
			case 4: setModificationRefId(((Integer) o).intValue()); break;
			case 5: setModificationRefDisplay((String) o); break;
			case 6: setCategoryRefId(((Integer) o).intValue()); break;
			case 7: setCategoryRefDisplay((String) o); break;
			case 8: setUniqueDisplayCodeInd(((Integer) o).intValue()); break;
			case 9: setFrameworkInd(((Integer) o).intValue()); break;
			case 10: setCreateDt((GregorianCalendar) o); break;
			case 11: setCreateUserId(((Integer) o).intValue()); break;
			case 12: setCreateUserName((String) o); break;
			case 13: setUpdateDt((GregorianCalendar) o); break;
			case 14: setUpdateUserId(((Integer) o).intValue()); break;
			case 15: setUpdateUserName((String) o); break;
			case 16: setUpdateCount(((Integer) o).intValue()); break;
			case 17: setActiveInd(((Integer) o).intValue()); break;
			case 18: setSystemAssignedVersionNbr(((Integer) o).intValue()); break;
			case 19: setRecordTypeRefId(((Integer) o).intValue()); break;
			case 20: setRecordTypeRefDisplay((String) o); break;
		}
	}

}