/*
     * The ReferenceGroup model is a domain object which stores the groups of related lookup table id
 * as gender, locations, applications etc.   The reference group id is used in the Reference table,
 * 
 * The ReferenceGroupDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by ReferenceGroupModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to ReferenceGroupModel.  The ReferenceGroupList is a collection
 * of ReferenceGroupModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.

    Copyright (C) 2006  Aron Lancout Smith

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

*/
package com.osframework.datalibrary.reference.common;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.GregorianCalendar;
import java.util.Vector;

import com.osframework.datalibrary.common.AccessDataTypeException;
import com.osframework.datalibrary.common.BaseAdapter;
import com.osframework.datalibrary.common.DataAccessException;
import com.osframework.datalibrary.common.DataUpdateException;
import com.osframework.datalibrary.common.Db;
import com.osframework.datalibrary.common.DbConnection;
import com.osframework.datalibrary.common.Null;
import com.osframework.datalibrary.common.SQLResult;
import com.osframework.datalibrary.common.UpdateResult;
import com.osframework.ejb.reference.common.IReferenceMap;
import com.osframework.ejb.reference.security.ISecurity;
import com.osframework.framework.exceptions.NullArgumentException;
import com.osframework.framework.logging.Debug;
import com.osframework.modellibrary.common.ServiceCall;
import com.osframework.modellibrary.reference.common.ReferenceGroupList;
import com.osframework.modellibrary.reference.common.ReferenceGroupModel;
import com.osframework.modellibrary.reference.group.RecordTypeFramework;
import com.osframework.modellibrary.reference.group.TableNameFramework;

/**
 * The ReferenceGroup model is a domain object which stores the groups of related lookup table id
 * as gender, locations, applications etc.   The reference group id is used in the Reference table,
 * 
 * The ReferenceGroupDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by ReferenceGroupModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to ReferenceGroupModel.  The ReferenceGroupList is a collection
 * of ReferenceGroupModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.
*/
public class ReferenceGroupDbAdapter extends BaseAdapter {
	

	private IReferenceMap reference;
	private ISecurity security;

	public ReferenceGroupDbAdapter(IReferenceMap reference, ISecurity security) {
		this.reference = reference;
		this.security = security;
	}


	public UpdateResult UpdateReferenceGroup(ReferenceGroupModel m, ServiceCall call) throws DataUpdateException {
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
			return UpdateReferenceGroup(m, call, conn);
		} catch (Exception ex) {
			throw new DataUpdateException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	}


	public UpdateResult UpdateReferenceGroup(ReferenceGroupModel m, ServiceCall call, DbConnection conn) throws DataUpdateException {
		ReferenceGroupModel original = null;
		try {
			if (m == null) {
				throw new NullArgumentException();
			}
			if (m.isNew()) {
				m.setCreateUserId(call.getUserId());
				m.setCreateDt(new GregorianCalendar());
			}
			if (m.hasModified()) {
				original = getReferenceGroup(m.getReferenceGroupId(), conn);
				m.setUpdateDt(new GregorianCalendar());
				m.setUpdateUserId(call.getUserId());
				m.setUpdateCount(original.getUpdateCount()+1);
				m.setSystemAssignedVersionNbr(1);
				m.copyModifiedTo(original);
				UpdateResult result = save(original, conn);
				m.setReferenceGroupId(original.getReferenceGroupId());
				return result;
			} else {
				return new UpdateResult();
			}
		} catch (Exception ex) {
			if (original != null) {
				Debug.LogException(this, ex, original.toString());
			} else {
				Debug.LogException(this, ex);
			}
			throw new DataUpdateException(ex); 
		}
	}
	
	private UpdateResult save(ReferenceGroupModel m, DbConnection conn) throws SQLException, AccessDataTypeException {
		int nbrRows = 0;
		String sql = "";
		SQLResult result = null;
		Vector params = null;
		try {
			if (m.getReferenceGroupId()==0) {
				m.setReferenceGroupId(Db.getNextSequence(TableNameFramework.REFERENCEGROUP, conn));
				sql = getInsertSql();
				params = getInsertParameters(m);
				result = Db.getAccess().executeUpdate(getInsertSql(), getInsertParameters(m), conn);
				nbrRows = result.getRowsUpdated();
			} else {
				sql = getUpdateSql();
				params = getInsertParameters(m);
				result = Db.getAccess().executeUpdate(getUpdateSql(), getUpdateParameters(m), conn);
				nbrRows = result.getRowsUpdated();
			}
			return new UpdateResult(nbrRows,m.getReferenceGroupId());
		} catch (SQLException ex) {
			Debug.LogError(ex.getMessage(), Db.getFormattedException(ex, sql, params));
			throw ex;
		}
	}
		
	protected int ImportReferenceGroup(ReferenceGroupModel m) throws SQLException, AccessDataTypeException {
		int nbrRows = 0;
		String sql = "";
		SQLResult result = null;
		Vector params = null;
		try {
			sql = getInsertSql();
			params = getInsertParameters(m);
			result = Db.getAccess().executeUpdate(getInsertSql(), getInsertParameters(m));
			nbrRows = result.getRowsUpdated();
			return nbrRows;
		} catch (SQLException ex) {
			Debug.LogError(ex.getMessage(), Db.getFormattedException(ex, sql, params));
			throw ex;
		}
	}
		
	public int DeleteReferenceGroup(ReferenceGroupModel m, DbConnection conn) throws DataUpdateException {
		SQLResult result = null;
		try {
			int nbrRows = 0;
			result = Db.getAccess().executeUpdate(getDeleteSql(), getDeleteParameters(m), conn);
			nbrRows = result.getRowsUpdated();
			return nbrRows;
		} catch (Exception ex) {
			Debug.LogException(this, ex);
			throw new DataUpdateException(ex);
		}
	}
	/**
	 * Maps the resultset to the model.
	 */
	public void mapReferenceGroup(ResultSet rset, ReferenceGroupModel m) throws SQLException {
		if (columnExists(rset, "reference_group_id")) {
			m.setReferenceGroupId(rset.getInt("reference_group_id"));
			if (rset.wasNull()) m.setReferenceGroupId(0);
		}
		if (columnExists(rset, "reference_group")) {
			m.setReferenceGroup(rset.getString("reference_group"));
			if (rset.wasNull()) m.setReferenceGroup(null);
		}
		if (columnExists(rset, "display")) {
			m.setDisplay(rset.getString("display"));
			if (rset.wasNull()) m.setDisplay(null);
		}
		if (columnExists(rset, "description")) {
			m.setDescription(rset.getString("description"));
			if (rset.wasNull()) m.setDescription(null);
		}
		if (columnExists(rset, "modification_ref_id")) {
			m.setModificationRefId(rset.getInt("modification_ref_id"));
			if (rset.wasNull()) m.setModificationRefId(0);
		}
		if (columnExists(rset, "category_ref_id")) {
			m.setCategoryRefId(rset.getInt("category_ref_id"));
			if (rset.wasNull()) m.setCategoryRefId(0);
		}
		if (columnExists(rset, "unique_display_code_ind")) {
			m.setUniqueDisplayCodeInd(rset.getInt("unique_display_code_ind"));
			if (rset.wasNull()) m.setUniqueDisplayCodeInd(0);
		}
		if (columnExists(rset, "framework_ind")) {
			m.setFrameworkInd(rset.getInt("framework_ind"));
			if (rset.wasNull()) m.setFrameworkInd(0);
		}
		if (columnExists(rset, "create_dt")) {
			m.setCreateDt(Db.getCalendarDate(rset.getTimestamp("create_dt")));
			if (rset.wasNull()) m.setCreateDt(null);
		}
		if (columnExists(rset, "create_user_id")) {
			m.setCreateUserId(rset.getInt("create_user_id"));
			if (rset.wasNull()) m.setCreateUserId(0);
		}
		if (columnExists(rset, "update_dt")) {
			m.setUpdateDt(Db.getCalendarDate(rset.getTimestamp("update_dt")));
			if (rset.wasNull()) m.setUpdateDt(null);
		}
		if (columnExists(rset, "update_user_id")) {
			m.setUpdateUserId(rset.getInt("update_user_id"));
			if (rset.wasNull()) m.setUpdateUserId(0);
		}
		if (columnExists(rset, "update_count")) {
			m.setUpdateCount(rset.getInt("update_count"));
			if (rset.wasNull()) m.setUpdateCount(0);
		}
		if (columnExists(rset, "active_ind")) {
			m.setActiveInd(rset.getInt("active_ind"));
			if (rset.wasNull()) m.setActiveInd(0);
		}
		if (columnExists(rset, "system_assigned_version_nbr")) {
			m.setSystemAssignedVersionNbr(rset.getInt("system_assigned_version_nbr"));
			if (rset.wasNull()) m.setSystemAssignedVersionNbr(0);
		}
		if (columnExists(rset, "record_type_ref_id")) {
			m.setRecordTypeRefId(rset.getInt("record_type_ref_id"));
			if (rset.wasNull()) m.setRecordTypeRefId(0);
		}
		m.resetModified();
	}

 /**
  * Execute the SQL and return a list for the result set
  */
	public ReferenceGroupList  getReferenceGroup(String sql) throws DataAccessException {
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
			return getReferenceGroup(sql, conn);
		} catch (Exception ex) {
			throw new DataAccessException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	} /**
  * Execute the SQL and return a list for the result set
  */
	public ReferenceGroupList  getReferenceGroup(String sql, DbConnection conn) throws DataAccessException {
		SQLResult result = null;
		try {
			ReferenceGroupList list = new ReferenceGroupList();
			result = Db.getAccess().executeQuery(sql, conn);
			ResultSet rset = result.getRset();
			while (rset.next()) {
				ReferenceGroupModel m = new ReferenceGroupModel();
				mapReferenceGroup(rset, m);
				list.add(m);
			}
			list.setReferenceDisplay(reference, security);
			return list;
		} catch (SQLException se) {
			Debug.LogError(this, Db.getFormattedException(se, sql));
			throw new DataAccessException(se);
		} finally {
			try { if (result!=null) result.closeStatements();} catch (Exception ex) {}
		}
	}

 /**
  * Execute the SQL and return a list for the result set
  */
	public ReferenceGroupList  getReferenceGroup(String sql, Vector params) throws DataAccessException {
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
		return getReferenceGroup(sql, params, conn);
		} catch (Exception ex) {
			throw new DataAccessException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	}

 /**
  * Execute the SQL and return a list for the result set
  */
	public ReferenceGroupList  getReferenceGroup(String sql, Vector params, DbConnection conn) throws DataAccessException {
		SQLResult result = null;
		try {
			ReferenceGroupList list = new ReferenceGroupList();
			result = Db.getAccess().executeQuery(sql, params, conn);
			ResultSet rset = result.getRset();
			while (rset.next()) {
				ReferenceGroupModel m = new ReferenceGroupModel();
				mapReferenceGroup(rset, m);
				list.add(m);
			}
			list.setReferenceDisplay(reference, security);
			return list;
		} catch (SQLException se) {
			Debug.LogError(this, Db.getFormattedException(se, sql, params));
			throw new DataAccessException(se);
		} catch (AccessDataTypeException ae) {
			throw new DataAccessException(ae);
		} finally {
			try { if (result!=null) result.closeStatements();} catch (Exception ex) {}
		}
	}

	/**
	 * Returns the model from the database.
	 * Returns an empty model if the id is 0 or not found
	 */
	public ReferenceGroupModel getReferenceGroup(int id) throws DataAccessException { 
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
			return getReferenceGroup(id, conn);
		} catch (Exception ex) {
			throw new DataAccessException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	}

	/**
	 * Returns the model from the database.
	 * Returns an empty model if the id is 0 or not found
	 */
	public ReferenceGroupModel getReferenceGroup(int id, DbConnection conn) throws DataAccessException { 
		SQLResult result = null;
		try {
			ReferenceGroupModel m = new ReferenceGroupModel();
			// TODO This fails if you actually wanted to get the zero row
			if (id > 0) {
				result = Db.getAccess().executeQuery(getSelectSql(), Db.getParameter(id), conn);
				ResultSet rset = result.getRset();
				if (rset.next()) {
					mapReferenceGroup(rset, m);
					m.resetModified();
				}
			}
			m.setReferenceDisplay(reference, security);
			return m;
		} catch (Exception ex) {
			Debug.LogException(this, ex, "ReferenceGroupModel" + id);
			throw new DataAccessException(ex);
		} finally {
			try { if (result!=null) result.closeStatements();} catch (Exception ex) {}
		}
	}

	public ReferenceGroupList exportReferenceGroup() throws DataAccessException {
		int rows = Db.countTable("reference_group");
		Debug.LogInfo(this, rows + " found in reference_group");
		String sql = "select * from reference_group where record_type_ref_id in (?, ?)";
		ReferenceGroupList list = this.getReferenceGroup(sql, Db.getParameter(RecordTypeFramework.SYSTEMREFERENCE, RecordTypeFramework.USERREFERENCE)); 
		Debug.LogInfo(this,list.size()  + " reference_group rows exported");
		return list;
	}

	public int importReferenceGroup(ReferenceGroupList list) throws Exception {
		Enumeration e1 = list.elements();
		int rows = 0;
		while (e1.hasMoreElements()) {
			ReferenceGroupModel m = (ReferenceGroupModel) e1.nextElement();
			rows += ImportReferenceGroup(m);
		}
		Debug.LogInfo(this, rows + " reference_group rows imported");
		return rows;
	}

	private String getSelectSql() {
		return "select reference_group_id, reference_group, display, description, "
			+ "modification_ref_id, category_ref_id, unique_display_code_ind, framework_ind, "
			+ "create_dt, create_user_id, update_dt, update_user_id, "
			+ "update_count, active_ind, system_assigned_version_nbr, record_type_ref_id"
			+ " from reference_group "
			+ " where reference_group_id = ?";				 
	}
	
	private String getInsertSql() {
		return "insert into reference_group (reference_group_id, reference_group, display, description, "
			+ "modification_ref_id, category_ref_id, unique_display_code_ind, framework_ind, "
			+ "create_dt, create_user_id, update_dt, update_user_id, "
			+ "update_count, active_ind, system_assigned_version_nbr, record_type_ref_id)"
			+ " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";				 
	}
	
	private Vector getInsertParameters(ReferenceGroupModel m) {
		Vector v = new Vector(16);
		v.add(new Integer(m.getReferenceGroupId()));
		if (m.getReferenceGroup() != null) v.add(m.getReferenceGroup());
		else v.add(new Null(new String()));
		if (m.getDisplay() != null) v.add(m.getDisplay());
		else v.add(new Null(new String()));
		if (m.getDescription() != null) v.add(m.getDescription());
		else v.add(new Null(new String()));
		v.add(new Integer(m.getModificationRefId()));
		v.add(new Integer(m.getCategoryRefId()));
		v.add(new Integer(m.getUniqueDisplayCodeInd()));
		v.add(new Integer(m.getFrameworkInd()));
		if (m.getCreateDt() != null) v.add(m.getCreateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getCreateUserId()));
		if (m.getUpdateDt() != null) v.add(m.getUpdateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getUpdateUserId()));
		v.add(new Integer(m.getUpdateCount()));
		v.add(new Integer(m.getActiveInd()));
		v.add(new Integer(m.getSystemAssignedVersionNbr()));
		v.add(new Integer(m.getRecordTypeRefId()));
		return v;
	}
	
	private String getUpdateSql() {
		return "update reference_group set  reference_group = ?, display = ?, description = ?, "
			+ "modification_ref_id = ?, category_ref_id = ?, unique_display_code_ind = ?, framework_ind = ?, "
			+ "create_dt = ?, create_user_id = ?, update_dt = ?, update_user_id = ?, "
			+ "update_count = ?, active_ind = ?, system_assigned_version_nbr = ?, record_type_ref_id = ? "
			+ " where reference_group_id = ?";				 
	}
	
	private Vector getUpdateParameters(ReferenceGroupModel m) {
		Vector v = new Vector(16);
		if (m.getReferenceGroup() != null) v.add(m.getReferenceGroup());
		else v.add(new Null(new String()));
		if (m.getDisplay() != null) v.add(m.getDisplay());
		else v.add(new Null(new String()));
		if (m.getDescription() != null) v.add(m.getDescription());
		else v.add(new Null(new String()));
		v.add(new Integer(m.getModificationRefId()));
		v.add(new Integer(m.getCategoryRefId()));
		v.add(new Integer(m.getUniqueDisplayCodeInd()));
		v.add(new Integer(m.getFrameworkInd()));
		if (m.getCreateDt() != null) v.add(m.getCreateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getCreateUserId()));
		if (m.getUpdateDt() != null) v.add(m.getUpdateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getUpdateUserId()));
		v.add(new Integer(m.getUpdateCount()));
		v.add(new Integer(m.getActiveInd()));
		v.add(new Integer(m.getSystemAssignedVersionNbr()));
		v.add(new Integer(m.getRecordTypeRefId()));
		v.add(new Integer(m.getReferenceGroupId()));
		return v;
	}

	private Vector getDeleteParameters(ReferenceGroupModel m) {
		Vector v = new Vector(16);
		v.add(new Integer(m.getReferenceGroupId()));
		return v;
	}

	private String getDeleteSql() {
		return "delete from reference_group where reference_group_id = ?";				 
	}

}
