/*
     * The ApplicationSetting model is a domain object which stores a users custom saved settings/preferences
 * 
 * The ApplicationSettingDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by ApplicationSettingModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to ApplicationSettingModel.  The ApplicationSettingList is a collection
 * of ApplicationSettingModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.

    Copyright (C) 2006  Aron Lancout Smith

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

*/
package com.osframework.modellibrary.reference.security;
import java.util.*;
import com.osframework.framework.locale.*;
import com.osframework.framework.logging.*;
import com.osframework.framework.utility.*;
import com.osframework.framework.exceptions.*;
import com.osframework.ejb.reference.common.*;
import com.osframework.ejb.reference.security.*;
import com.osframework.modellibrary.common.*;
import com.osframework.modellibrary.reference.group.*;
import com.osframework.appclient.services.*;
import com.osframework.modellibrary.reference.security.*;

/**
 * The ApplicationSetting model is a domain object which stores a users custom saved settings/preferences
 * 
 * The ApplicationSettingDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by ApplicationSettingModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to ApplicationSettingModel.  The ApplicationSettingList is a collection
 * of ApplicationSettingModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.
*/
public class ApplicationSettingDataModel implements IControlModel, java.io.Serializable {

	static final long serialVersionUID = 1L;
	private int hashsize = 18;
	private Hashtable modifiedFields = new Hashtable(hashsize);
	private boolean referenceSet = false;


	/** Unique application setting identifier  */
	private int applicationSettingId = 0;

	/** Foreign key of related table  */
	private int tableKeyId = 0;

	/** Foreign key of reference  */
	private int tableRefId = 0;

	private String tableRefDisplay="";

	/** Unique application setting identifier  */
	private int applicationViewId = 0;

	/** Reference setting id  */
	private int settingRefId = 0;

	private String settingRefDisplay="";

	/** Foreign key to reference: DatabaseDataType  */
	private int dataTypeRefId = 0;

	private String dataTypeRefDisplay="";

	/** Integer data value  */
	private int valueInt;

	/** Double data value  */
	private double valueDouble;

	/** String value  */
	private String valueString;

	/** Date value  */
	private DbCalendar valueDate;

	/** Date the record was created  */
	private DbCalendar createDt = DbCalendar.getDbCalendar();

	/** User that created this record  */
	private int createUserId = 0;

	private String createUserName="";

	/** Date the record was updated  */
	private DbCalendar updateDt = DbCalendar.getDbCalendar();

	/** Date the record was last updated  */
	private int updateUserId = 0;

	private String updateUserName="";

	/** Number of times this record has been updated  */
	private int updateCount = 0;

	/** Active indicator 1=Active 0=Inactive  */
	private int activeInd = 1;

	/** 0: Customer defined >0:   */
	private int systemAssignedVersionNbr = 5;

	/** Identifies database row as Reference or Record and System or User entered  */
	private int recordTypeRefId = 321;

	private String recordTypeRefDisplay="";


	/** 
	 * Unique application setting identifier
	 * 
	 */ 
	public int getApplicationSettingId() {
		return applicationSettingId;
	}

	/** 
	 * Unique application setting identifier
	 * 
	 * Required database field.
	 */ 
	public void setApplicationSettingId(int applicationSettingId) {
		if (!Comparison.areEqual(this.applicationSettingId, applicationSettingId)) {
			this.applicationSettingId = applicationSettingId;
			setModified("applicationSettingId");
		};
	}

	/** 
	 * Foreign key of related table
	 * 
	 */ 
	public int getTableKeyId() {
		return tableKeyId;
	}

	/** 
	 * Foreign key of related table
	 * 
	 * Required database field.
	 */ 
	public void setTableKeyId(int tableKeyId) {
		if (!Comparison.areEqual(this.tableKeyId, tableKeyId)) {
			this.tableKeyId = tableKeyId;
			setModified("tableKeyId");
		};
	}

	/** 
	 * Foreign key of reference
	 * 
	 */ 
	public int getTableRefId() {
		return tableRefId;
	}

	/** 
	 * Foreign key of reference
	 * 
	 * Required database field.
	 */ 
	public void setTableRefId(int tableRefId) {
		if (!Comparison.areEqual(this.tableRefId, tableRefId)) {
			this.tableRefId = tableRefId;
			setModified("tableRefId");
		};
	}

	/** 
	 * Foreign key of reference
	 * 
	 */ 
	public String getTableRefDisplay() {
		return tableRefDisplay;
	}

	/** 
	 * Foreign key of reference
	 * 
	 */ 
	public void setTableRefDisplay(String display) {
		this.tableRefDisplay = display;
	}

	/** 
	 * Unique application setting identifier
	 * 
	 */ 
	public int getApplicationViewId() {
		return applicationViewId;
	}

	/** 
	 * Unique application setting identifier
	 * 
	 * Required database field.
	 */ 
	public void setApplicationViewId(int applicationViewId) {
		if (!Comparison.areEqual(this.applicationViewId, applicationViewId)) {
			this.applicationViewId = applicationViewId;
			setModified("applicationViewId");
		};
	}

	/** 
	 * Reference setting id
	 * 
	 */ 
	public int getSettingRefId() {
		return settingRefId;
	}

	/** 
	 * Reference setting id
	 * 
	 * Required database field.
	 */ 
	public void setSettingRefId(int settingRefId) {
		if (!Comparison.areEqual(this.settingRefId, settingRefId)) {
			this.settingRefId = settingRefId;
			setModified("settingRefId");
		};
	}

	/** 
	 * Reference setting id
	 * 
	 */ 
	public String getSettingRefDisplay() {
		return settingRefDisplay;
	}

	/** 
	 * Reference setting id
	 * 
	 */ 
	public void setSettingRefDisplay(String display) {
		this.settingRefDisplay = display;
	}

	/** 
	 * Foreign key to reference: DatabaseDataType
	 * 
	 */ 
	public int getDataTypeRefId() {
		return dataTypeRefId;
	}

	/** 
	 * Foreign key to reference: DatabaseDataType
	 * 
	 * Required database field.
	 */ 
	public void setDataTypeRefId(int dataTypeRefId) {
		if (!Comparison.areEqual(this.dataTypeRefId, dataTypeRefId)) {
			this.dataTypeRefId = dataTypeRefId;
			setModified("dataTypeRefId");
		};
	}

	/** 
	 * Foreign key to reference: DatabaseDataType
	 * 
	 */ 
	public String getDataTypeRefDisplay() {
		return dataTypeRefDisplay;
	}

	/** 
	 * Foreign key to reference: DatabaseDataType
	 * 
	 */ 
	public void setDataTypeRefDisplay(String display) {
		this.dataTypeRefDisplay = display;
	}

	/** 
	 * Integer data value
	 * 
	 */ 
	public int getValueInt() {
		return valueInt;
	}

	/** 
	 * Integer data value
	 * 
	 */ 
	public void setValueInt(int valueInt) {
		if (!Comparison.areEqual(this.valueInt, valueInt)) {
			this.valueInt = valueInt;
			setModified("valueInt");
		};
	}

	/** 
	 * Double data value
	 * 
	 */ 
	public double getValueDouble() {
		return valueDouble;
	}

	/** 
	 * Double data value
	 * 
	 */ 
	public void setValueDouble(double valueDouble) {
		if (!Comparison.areEqual(this.valueDouble, valueDouble)) {
			this.valueDouble = valueDouble;
			setModified("valueDouble");
		};
	}

	/** 
	 * String value
	 * 
	 */ 
	public String getValueString() {
		return valueString;
	}

	/** 
	 * String value
	 * 
	 */ 
	public void setValueString(String valueString) {
		if (!Comparison.areEqual(this.valueString, valueString)) {
			this.valueString = valueString;
			setModified("valueString");
		};
	}

	/** 
	 * Date value
	 * 
	 */ 
	public DbCalendar getValueDate() {
		return valueDate;
	}

	/** 
	 * Date value
	 * 
	 */ 
	public void setValueDate(GregorianCalendar valueDate) {
		if (!Comparison.areEqual(this.valueDate, valueDate)) {
			this.valueDate = new DbCalendar();
			if (valueDate != null) {
				this.valueDate.setTimeInMillis(valueDate.getTimeInMillis());
			}
			setModified("valueDate");
		};
	}

	/** 
	 * Date value
	 * 
	 */ 
	public void setValueDate(long milliseconds) {
		if (this.valueDate==null) {
			this.valueDate = new DbCalendar();
		}
		if (!Comparison.areEqual(this.valueDate, valueDate)) {
			this.valueDate.setTimeInMillis(milliseconds);
			setModified("valueDate");
		}

	}

	/** 
	 * Date the record was created
	 * 
	 */ 
	public DbCalendar getCreateDt() {
		return createDt;
	}

	/** 
	 * Date the record was created
	 * 
	 */ 
	public void setCreateDt(GregorianCalendar createDt) {
		if (!Comparison.areEqual(this.createDt, createDt)) {
			this.createDt = new DbCalendar();
			if (createDt != null) {
				this.createDt.setTimeInMillis(createDt.getTimeInMillis());
			}
			setModified("createDt");
		};
	}

	/** 
	 * Date the record was created
	 * 
	 */ 
	public void setCreateDt(long milliseconds) {
		if (this.createDt==null) {
			this.createDt = new DbCalendar();
		}
		if (!Comparison.areEqual(this.createDt, createDt)) {
			this.createDt.setTimeInMillis(milliseconds);
			setModified("createDt");
		}

	}

	/** 
	 * User that created this record
	 * 
	 */ 
	public int getCreateUserId() {
		return createUserId;
	}

	/** 
	 * User that created this record
	 * 
	 * Required database field.
	 */ 
	public void setCreateUserId(int createUserId) {
		if (!Comparison.areEqual(this.createUserId, createUserId)) {
			this.createUserId = createUserId;
			setModified("createUserId");
		};
	}

	/** 
	 * User that created this record
	 * 
	 */ 
	public String getCreateUserName() {
		return createUserName;
	}

	/** 
	 * User that created this record
	 * 
	 */ 
	public void setCreateUserName(String userName) {
		this.createUserName = userName;
	}

	/** 
	 * Date the record was updated
	 * 
	 */ 
	public DbCalendar getUpdateDt() {
		return updateDt;
	}

	/** 
	 * Date the record was updated
	 * 
	 */ 
	public void setUpdateDt(GregorianCalendar updateDt) {
		if (!Comparison.areEqual(this.updateDt, updateDt)) {
			this.updateDt = new DbCalendar();
			if (updateDt != null) {
				this.updateDt.setTimeInMillis(updateDt.getTimeInMillis());
			}
			setModified("updateDt");
		};
	}

	/** 
	 * Date the record was updated
	 * 
	 */ 
	public void setUpdateDt(long milliseconds) {
		if (this.updateDt==null) {
			this.updateDt = new DbCalendar();
		}
		if (!Comparison.areEqual(this.updateDt, updateDt)) {
			this.updateDt.setTimeInMillis(milliseconds);
			setModified("updateDt");
		}

	}

	/** 
	 * Date the record was last updated
	 * 
	 */ 
	public int getUpdateUserId() {
		return updateUserId;
	}

	/** 
	 * Date the record was last updated
	 * 
	 * Required database field.
	 */ 
	public void setUpdateUserId(int updateUserId) {
		if (!Comparison.areEqual(this.updateUserId, updateUserId)) {
			this.updateUserId = updateUserId;
			setModified("updateUserId");
		};
	}

	/** 
	 * Date the record was last updated
	 * 
	 */ 
	public String getUpdateUserName() {
		return updateUserName;
	}

	/** 
	 * Date the record was last updated
	 * 
	 */ 
	public void setUpdateUserName(String userName) {
		this.updateUserName = userName;
	}

	/** 
	 * Number of times this record has been updated
	 * 
	 */ 
	public int getUpdateCount() {
		return updateCount;
	}

	/** 
	 * Number of times this record has been updated
	 * 
	 * Required database field.
	 */ 
	public void setUpdateCount(int updateCount) {
		if (!Comparison.areEqual(this.updateCount, updateCount)) {
			this.updateCount = updateCount;
			setModified("updateCount");
		};
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public int getActiveInd() {
		return activeInd;
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 * Required database field.
	 */ 
	public void setActiveInd(int activeInd) {
		if (!Comparison.areEqual(this.activeInd, activeInd)) {
			this.activeInd = activeInd;
			setModified("activeInd");
		};
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public boolean isActive() {
		return activeInd == 1;
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public boolean isNotActive() {
		return activeInd == 0;
	}

	/** 
	 * Active indicator 1=Active 0=Inactive
	 * 
	 */ 
	public void setActive() {
		this.setActiveInd(1);
	}

	public void setNotActive() {
		this.setActiveInd(0);
	}

	/** 
	 * 0: Customer defined >0: 
	 * 
	 */ 
	public int getSystemAssignedVersionNbr() {
		return systemAssignedVersionNbr;
	}

	/** 
	 * 0: Customer defined >0: 
	 * 
	 * Required database field.
	 */ 
	public void setSystemAssignedVersionNbr(int systemAssignedVersionNbr) {
		if (!Comparison.areEqual(this.systemAssignedVersionNbr, systemAssignedVersionNbr)) {
			this.systemAssignedVersionNbr = systemAssignedVersionNbr;
			setModified("systemAssignedVersionNbr");
		};
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 */ 
	public int getRecordTypeRefId() {
		return recordTypeRefId;
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 * Required database field.
	 */ 
	public void setRecordTypeRefId(int recordTypeRefId) {
		if (!Comparison.areEqual(this.recordTypeRefId, recordTypeRefId)) {
			this.recordTypeRefId = recordTypeRefId;
			setModified("recordTypeRefId");
		};
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 */ 
	public String getRecordTypeRefDisplay() {
		return recordTypeRefDisplay;
	}

	/** 
	 * Identifies database row as Reference or Record and System or User entered
	 * 
	 */ 
	public void setRecordTypeRefDisplay(String display) {
		this.recordTypeRefDisplay = display;
	}


public static ResultColumnList getResultColumnList() {
	ResultColumnList columns = new ResultColumnList();
		columns.addColumn("applicationSettingId", Integer.class);
		columns.addColumn("tableKeyId", Integer.class);
		columns.addColumn("tableRefId", Integer.class);
		columns.addColumn("tableRefDisplay", String.class);
		columns.addColumn("applicationViewId", Integer.class);
		columns.addColumn("settingRefId", Integer.class);
		columns.addColumn("settingRefDisplay", String.class);
		columns.addColumn("dataTypeRefId", Integer.class);
		columns.addColumn("dataTypeRefDisplay", String.class);
		columns.addColumn("valueInt", Integer.class);
		columns.addColumn("valueDouble", Double.class);
		columns.addColumn("valueString", String.class);
		columns.addColumn("valueDate", GregorianCalendar.class);
		columns.addColumn("createDt", GregorianCalendar.class);
		columns.addColumn("createUserId", Integer.class);
		columns.addColumn("createUserName", String.class);
		columns.addColumn("updateDt", GregorianCalendar.class);
		columns.addColumn("updateUserId", Integer.class);
		columns.addColumn("updateUserName", String.class);
		columns.addColumn("updateCount", Integer.class);
		columns.addColumn("activeInd", Integer.class);
		columns.addColumn("systemAssignedVersionNbr", Integer.class);
		columns.addColumn("recordTypeRefId", Integer.class);
		columns.addColumn("recordTypeRefDisplay", String.class);
		return columns;
	}
		
	/** 
	 * Flags this field as being modified
	 */ 
	public void setReferenceDisplay(IReferenceMap reference, ISecurity security) {
		try {
			if (referenceSet) {
				return;
			}
		referenceSet = true;
			if (reference != null && this.tableRefId > 0) setTableRefDisplay(reference.getDisplay(this.tableRefId));
			if (reference != null && this.settingRefId > 0) setSettingRefDisplay(reference.getDisplay(this.settingRefId));
			if (reference != null && this.dataTypeRefId > 0) setDataTypeRefDisplay(reference.getDisplay(this.dataTypeRefId));
			if (security != null && this.createUserId > 0) setCreateUserName(security.getUser(this.createUserId).getDisplayName());
			if (security != null && this.updateUserId > 0) setUpdateUserName(security.getUser(this.updateUserId).getDisplayName());
			if (reference != null && this.recordTypeRefId > 0) setRecordTypeRefDisplay(reference.getDisplay(this.recordTypeRefId));
		} catch (Exception e) {
			Debug.LogException(this, e);
		}
	}		
	/** 
	 * Flags this field as being modified
	 */ 
	public void setModified(String fieldName) {
		if (!modifiedFields.containsKey(fieldName)) {
			modifiedFields.put(fieldName, "1");
		}
	}

	/** 
	 * Resets flagged fields so none are marked as modified
	 */ 
	public void resetModified() {
		modifiedFields = new Hashtable(hashsize);
	}

	public boolean hasModified() {
		return modifiedFields.size() > 0;
	}

	
		
	/** 
	 * Copys the values of all modified fields to object m
	 */ 
	public void copyModifiedTo(ApplicationSettingDataModel m) {
		Enumeration e1 = modifiedFields.keys();
		while (e1.hasMoreElements()) {
			String fieldName = (String) e1.nextElement();

			if (fieldName.compareTo("applicationSettingId")==0)
				m.setApplicationSettingId(this.getApplicationSettingId());
			else if (fieldName.compareTo("tableKeyId")==0)
				m.setTableKeyId(this.getTableKeyId());
			else if (fieldName.compareTo("tableRefId")==0)
				m.setTableRefId(this.getTableRefId());
			else if (fieldName.compareTo("applicationViewId")==0)
				m.setApplicationViewId(this.getApplicationViewId());
			else if (fieldName.compareTo("settingRefId")==0)
				m.setSettingRefId(this.getSettingRefId());
			else if (fieldName.compareTo("dataTypeRefId")==0)
				m.setDataTypeRefId(this.getDataTypeRefId());
			else if (fieldName.compareTo("valueInt")==0)
				m.setValueInt(this.getValueInt());
			else if (fieldName.compareTo("valueDouble")==0)
				m.setValueDouble(this.getValueDouble());
			else if (fieldName.compareTo("valueString")==0)
				m.setValueString(this.getValueString());
			else if (fieldName.compareTo("valueDate")==0)
				m.setValueDate(this.getValueDate());
			else if (fieldName.compareTo("createDt")==0)
				m.setCreateDt(this.getCreateDt());
			else if (fieldName.compareTo("createUserId")==0)
				m.setCreateUserId(this.getCreateUserId());
			else if (fieldName.compareTo("updateDt")==0)
				m.setUpdateDt(this.getUpdateDt());
			else if (fieldName.compareTo("updateUserId")==0)
				m.setUpdateUserId(this.getUpdateUserId());
			else if (fieldName.compareTo("updateCount")==0)
				m.setUpdateCount(this.getUpdateCount());
			else if (fieldName.compareTo("activeInd")==0)
				m.setActiveInd(this.getActiveInd());
			else if (fieldName.compareTo("systemAssignedVersionNbr")==0)
				m.setSystemAssignedVersionNbr(this.getSystemAssignedVersionNbr());
			else if (fieldName.compareTo("recordTypeRefId")==0)
				m.setRecordTypeRefId(this.getRecordTypeRefId());
			else 		
				Debug.LogError(this, ExceptionInfo.invalidCopyModifiedField + " " + fieldName);
	}
}

	/**
	 * Update this object with the data from m
	 */
	public void updateWith (ApplicationSettingModel m) {

		this.setApplicationSettingId(m.getApplicationSettingId());
		this.setTableKeyId(m.getTableKeyId());
		this.setTableRefId(m.getTableRefId());
		this.setTableRefDisplay(m.getTableRefDisplay());
		this.setApplicationViewId(m.getApplicationViewId());
		this.setSettingRefId(m.getSettingRefId());
		this.setSettingRefDisplay(m.getSettingRefDisplay());
		this.setDataTypeRefId(m.getDataTypeRefId());
		this.setDataTypeRefDisplay(m.getDataTypeRefDisplay());
		this.setValueInt(m.getValueInt());
		this.setValueDouble(m.getValueDouble());
		this.setValueString(m.getValueString());
		this.setValueDate(m.getValueDate());
		this.setCreateDt(m.getCreateDt());
		this.setCreateUserId(m.getCreateUserId());
		this.setCreateUserName(m.getCreateUserName());
		this.setUpdateDt(m.getUpdateDt());
		this.setUpdateUserId(m.getUpdateUserId());
		this.setUpdateUserName(m.getUpdateUserName());
		this.setUpdateCount(m.getUpdateCount());
		this.setActiveInd(m.getActiveInd());
		this.setSystemAssignedVersionNbr(m.getSystemAssignedVersionNbr());
		this.setRecordTypeRefId(m.getRecordTypeRefId());
		this.setRecordTypeRefDisplay(m.getRecordTypeRefDisplay());
	}

	/**
	 * Compare the two objects
	 */
	public boolean isEqualTo (ApplicationSettingModel m) {

		if (!Comparison.areEqual(this.getApplicationSettingId(),  m.getApplicationSettingId())) return false;
		if (!Comparison.areEqual(this.getTableKeyId(),  m.getTableKeyId())) return false;
		if (!Comparison.areEqual(this.getTableRefId(),  m.getTableRefId())) return false;
		if (!Comparison.areEqual(this.getApplicationViewId(),  m.getApplicationViewId())) return false;
		if (!Comparison.areEqual(this.getSettingRefId(),  m.getSettingRefId())) return false;
		if (!Comparison.areEqual(this.getDataTypeRefId(),  m.getDataTypeRefId())) return false;
		if (!Comparison.areEqual(this.getValueInt(),  m.getValueInt())) return false;
		if (!Comparison.areEqual(this.getValueDouble(),  m.getValueDouble())) return false;
		if (!Comparison.areEqual(this.getValueString(),  m.getValueString())) return false;
		if (!Comparison.areEqual(this.getValueDate(),  m.getValueDate())) return false;
		if (!Comparison.areEqual(this.getCreateDt(),  m.getCreateDt())) return false;
		if (!Comparison.areEqual(this.getCreateUserId(),  m.getCreateUserId())) return false;
		if (!Comparison.areEqual(this.getUpdateCount(),  m.getUpdateCount())) return false;
		if (!Comparison.areEqual(this.getActiveInd(),  m.getActiveInd())) return false;
		if (!Comparison.areEqual(this.getSystemAssignedVersionNbr(),  m.getSystemAssignedVersionNbr())) return false;
		if (!Comparison.areEqual(this.getRecordTypeRefId(),  m.getRecordTypeRefId())) return false;
		return true;
	}
	/**
	 * Returns a list of all field names which are required and are null
	 */
	public Vector getMissingRequired () {

		Vector v = new Vector();
		return v;
	}
	public String toString() {
		try {
			StringBuffer sb = new StringBuffer(1024);
			sb.append("ApplicationSettingModel:\r\n");
			sb.append("application_setting_id:" + getApplicationSettingId());
			sb.append("\r\n");
			sb.append("table_key_id:" + getTableKeyId());
			sb.append("\r\n");
			sb.append("table_ref_id:" + getTableRefId());
			sb.append("\r\n");
			sb.append("table_ref_display:" + getTableRefDisplay());
			sb.append("\r\n");
			sb.append("application_view_id:" + getApplicationViewId());
			sb.append("\r\n");
			sb.append("setting_ref_id:" + getSettingRefId());
			sb.append("\r\n");
			sb.append("setting_ref_display:" + getSettingRefDisplay());
			sb.append("\r\n");
			sb.append("data_type_ref_id:" + getDataTypeRefId());
			sb.append("\r\n");
			sb.append("data_type_ref_display:" + getDataTypeRefDisplay());
			sb.append("\r\n");
			sb.append("value_int:" + getValueInt());
			sb.append("\r\n");
			sb.append("value_double:" + getValueDouble());
			sb.append("\r\n");
			sb.append("value_string:" + getValueString());
			sb.append("\r\n");
			sb.append("value_date:" + CalendarUtility.Format(getValueDate(),AppFormats.getLongDateTimeFormat()));
			sb.append("\r\n");
			sb.append("create_dt:" + CalendarUtility.Format(getCreateDt(),AppFormats.getLongDateTimeFormat()));
			sb.append("\r\n");
			sb.append("create_user_id:" + getCreateUserId());
			sb.append("\r\n");
			sb.append("create_user_name:" + getCreateUserName());
			sb.append("\r\n");
			sb.append("update_dt:" + CalendarUtility.Format(getUpdateDt(),AppFormats.getLongDateTimeFormat()));
			sb.append("\r\n");
			sb.append("update_user_id:" + getUpdateUserId());
			sb.append("\r\n");
			sb.append("update_user_name:" + getUpdateUserName());
			sb.append("\r\n");
			sb.append("update_count:" + getUpdateCount());
			sb.append("\r\n");
			sb.append("active_ind:" + getActiveInd());
			sb.append("\r\n");
			sb.append("system_assigned_version_nbr:" + getSystemAssignedVersionNbr());
			sb.append("\r\n");
			sb.append("record_type_ref_id:" + getRecordTypeRefId());
			sb.append("\r\n");
			sb.append("record_type_ref_display:" + getRecordTypeRefDisplay());
			sb.append("\r\n");
			return sb.toString();
		} catch (Exception ex) {
			return "ApplicationSettingModel:"; 
		}
	}
	public void setModelColDataAt(Object o, int modelCol) {
			switch (modelCol) {
			case 552: setApplicationSettingId(((Integer) o).intValue()); break;
			case 941: setTableKeyId(((Integer) o).intValue()); break;
			case 942: setTableRefId(((Integer) o).intValue()); break;
			case 1106: setApplicationViewId(((Integer) o).intValue()); break;
			case 555: setSettingRefId(((Integer) o).intValue()); break;
			case 1107: setDataTypeRefId(((Integer) o).intValue()); break;
			case 1108: setValueInt(((Integer) o).intValue()); break;
			case 1109: setValueDouble(((Double) o).doubleValue()); break;
			case 1110: setValueString((String) o); break;
			case 1111: setValueDate((GregorianCalendar) o); break;
			case 557: setCreateDt((GregorianCalendar) o); break;
			case 558: setCreateUserId(((Integer) o).intValue()); break;
			case 813: setCreateUserName((String) o); break;
			case 559: setUpdateDt((GregorianCalendar) o); break;
			case 560: setUpdateUserId(((Integer) o).intValue()); break;
			case 814: setUpdateUserName((String) o); break;
			case 561: setUpdateCount(((Integer) o).intValue()); break;
			case 562: setActiveInd(((Integer) o).intValue()); break;
			case 563: setSystemAssignedVersionNbr(((Integer) o).intValue()); break;
			case 564: setRecordTypeRefId(((Integer) o).intValue()); break;
			default: Debug.LogWarning(this, ReferenceServices.getMsg(SystemMessageFramework.SWITCHSTATEMENTFAILED) + " modelColRefId: " + modelCol);
	} 
}

	public Object getModelColDataAt(int modelCol) {
			if (modelCol == 552) return new Integer(applicationSettingId);
			if (modelCol == 941) return new Integer(tableKeyId);
			if (modelCol == 942) return new Integer(tableRefId);
			if (modelCol == 942) return tableRefDisplay;
			if (modelCol == 1106) return new Integer(applicationViewId);
			if (modelCol == 555) return new Integer(settingRefId);
			if (modelCol == 555) return settingRefDisplay;
			if (modelCol == 1107) return new Integer(dataTypeRefId);
			if (modelCol == 1107) return dataTypeRefDisplay;
			if (modelCol == 1108) return new Integer(valueInt);
			if (modelCol == 1109) return new Double(valueDouble);
			if (modelCol == 1110) return valueString;
			if (modelCol == 1111) return valueDate;
			if (modelCol == 557) return createDt;
			if (modelCol == 558) return new Integer(createUserId);
			if (modelCol == 558) return createUserName;
			if (modelCol == 559) return updateDt;
			if (modelCol == 560) return new Integer(updateUserId);
			if (modelCol == 560) return updateUserName;
			if (modelCol == 561) return new Integer(updateCount);
			if (modelCol == 562) return new Integer(activeInd);
			if (modelCol == 563) return new Integer(systemAssignedVersionNbr);
			if (modelCol == 564) return new Integer(recordTypeRefId);
			if (modelCol == 564) return recordTypeRefDisplay;
		return null;
	}

	public int getModelColDatabaseDataType(int modelCol) {
			if (modelCol == 552) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 941) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 942) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 942) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 1106) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 555) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 555) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 1107) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 1107) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 1108) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 1109) return DatabaseDataTypeFramework.DOUBLE;
			if (modelCol == 1110) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 1111) return DatabaseDataTypeFramework.DATE;
			if (modelCol == 557) return DatabaseDataTypeFramework.DATE;
			if (modelCol == 558) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 558) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 559) return DatabaseDataTypeFramework.DATE;
			if (modelCol == 560) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 560) return DatabaseDataTypeFramework.STRING;
			if (modelCol == 561) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 562) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 563) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 564) return DatabaseDataTypeFramework.INTEGER;
			if (modelCol == 564) return DatabaseDataTypeFramework.STRING;
			return DatabaseDataTypeFramework.STRING;
	}

	public boolean isNew() {
		return getApplicationSettingId() == 0;
	}

	public Object getPrimaryValue() {
		return new Integer(getApplicationSettingId());
	}

	public Object getDataAt(int i) {
			if (i == 0) return new Integer(applicationSettingId);
			if (i == 1) return new Integer(tableKeyId);
			if (i == 2) return new Integer(tableRefId);
			if (i == 3) return tableRefDisplay;
			if (i == 4) return new Integer(applicationViewId);
			if (i == 5) return new Integer(settingRefId);
			if (i == 6) return settingRefDisplay;
			if (i == 7) return new Integer(dataTypeRefId);
			if (i == 8) return dataTypeRefDisplay;
			if (i == 9) return new Integer(valueInt);
			if (i == 10) return new Double(valueDouble);
			if (i == 11) return valueString;
			if (i == 12) return valueDate;
			if (i == 13) return createDt;
			if (i == 14) return new Integer(createUserId);
			if (i == 15) return createUserName;
			if (i == 16) return updateDt;
			if (i == 17) return new Integer(updateUserId);
			if (i == 18) return updateUserName;
			if (i == 19) return new Integer(updateCount);
			if (i == 20) return new Integer(activeInd);
			if (i == 21) return new Integer(systemAssignedVersionNbr);
			if (i == 22) return new Integer(recordTypeRefId);
			if (i == 23) return recordTypeRefDisplay;
		return null;
	}

	public int getDatabaseDataType(int i) {
			if (i == 0) return DatabaseDataTypeFramework.INTEGER;
			if (i == 1) return DatabaseDataTypeFramework.INTEGER;
			if (i == 2) return DatabaseDataTypeFramework.INTEGER;
			if (i == 3) return DatabaseDataTypeFramework.STRING;
			if (i == 4) return DatabaseDataTypeFramework.INTEGER;
			if (i == 5) return DatabaseDataTypeFramework.INTEGER;
			if (i == 6) return DatabaseDataTypeFramework.STRING;
			if (i == 7) return DatabaseDataTypeFramework.INTEGER;
			if (i == 8) return DatabaseDataTypeFramework.STRING;
			if (i == 9) return DatabaseDataTypeFramework.INTEGER;
			if (i == 10) return DatabaseDataTypeFramework.DOUBLE;
			if (i == 11) return DatabaseDataTypeFramework.STRING;
			if (i == 12) return DatabaseDataTypeFramework.DATE;
			if (i == 13) return DatabaseDataTypeFramework.DATE;
			if (i == 14) return DatabaseDataTypeFramework.INTEGER;
			if (i == 15) return DatabaseDataTypeFramework.STRING;
			if (i == 16) return DatabaseDataTypeFramework.DATE;
			if (i == 17) return DatabaseDataTypeFramework.INTEGER;
			if (i == 18) return DatabaseDataTypeFramework.STRING;
			if (i == 19) return DatabaseDataTypeFramework.INTEGER;
			if (i == 20) return DatabaseDataTypeFramework.INTEGER;
			if (i == 21) return DatabaseDataTypeFramework.INTEGER;
			if (i == 22) return DatabaseDataTypeFramework.INTEGER;
			if (i == 23) return DatabaseDataTypeFramework.STRING;
			return DatabaseDataTypeFramework.STRING;
	}

	public void setDataAt(Object o, int i) {
		switch(i) {
			case 0: setApplicationSettingId(((Integer) o).intValue()); break;
			case 1: setTableKeyId(((Integer) o).intValue()); break;
			case 2: setTableRefId(((Integer) o).intValue()); break;
			case 3: setTableRefDisplay((String) o); break;
			case 4: setApplicationViewId(((Integer) o).intValue()); break;
			case 5: setSettingRefId(((Integer) o).intValue()); break;
			case 6: setSettingRefDisplay((String) o); break;
			case 7: setDataTypeRefId(((Integer) o).intValue()); break;
			case 8: setDataTypeRefDisplay((String) o); break;
			case 9: setValueInt(((Integer) o).intValue()); break;
			case 10: setValueDouble(((Double) o).doubleValue()); break;
			case 11: setValueString((String) o); break;
			case 12: setValueDate((GregorianCalendar) o); break;
			case 13: setCreateDt((GregorianCalendar) o); break;
			case 14: setCreateUserId(((Integer) o).intValue()); break;
			case 15: setCreateUserName((String) o); break;
			case 16: setUpdateDt((GregorianCalendar) o); break;
			case 17: setUpdateUserId(((Integer) o).intValue()); break;
			case 18: setUpdateUserName((String) o); break;
			case 19: setUpdateCount(((Integer) o).intValue()); break;
			case 20: setActiveInd(((Integer) o).intValue()); break;
			case 21: setSystemAssignedVersionNbr(((Integer) o).intValue()); break;
			case 22: setRecordTypeRefId(((Integer) o).intValue()); break;
			case 23: setRecordTypeRefDisplay((String) o); break;
		}
	}

}