//************ AUTO GENERATED DO NOT EDIT *********//
package com.osrmt.modellibrary.reqmanager;


/**
 * The ReferenceTree model is a domain object which stores lookup table id which have a parent/child
 * relationship such as locations, security etc.   The reference id maps to a row in the Reference table,
 * this table defines the relationship. Example the reference table may have
 *   id  Group       Display 
 *    8  Workflow    Discharge patient
 *    9  Workflow    Register patient
 *   10      Task    Modify patient
 *   11      Task    Add patient      
 * In the referencetree table we define that the modifypatient task is related to
 * both Discharge and Register
 *   ref id      parent ref id
 *       10                  8
 *       10                  9
 *       
 * The ReferenceTreeDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by ReferenceTreeModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to ReferenceTreeModel.  The ReferenceTreeList is a collection
 * of ReferenceTreeModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.
*/
public class RequirementTreeModel extends RequirementTreeDataModel implements Comparable {

	private static final long serialVersionUID = 1L;
	public RequirementTreeModel() {

	}
	
	public int compareTo(Object arg0) {
		return 0;
	}

}