/*
     * The User model is a domain object which stores the system application users
 * The user id is used throughout all tables following the convention <field>_user_id
 * e.g. create_user_id
 * The UserDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by UserModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to UserModel.  The UserList is a collection
 * of UserModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.

    Copyright (C) 2006  Aron Lancout Smith

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

*/
package com.osframework.datalibrary.reference.security;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.GregorianCalendar;
import java.util.Vector;

import com.osframework.datalibrary.common.AccessDataTypeException;
import com.osframework.datalibrary.common.BaseAdapter;
import com.osframework.datalibrary.common.DataAccessException;
import com.osframework.datalibrary.common.DataUpdateException;
import com.osframework.datalibrary.common.Db;
import com.osframework.datalibrary.common.DbConnection;
import com.osframework.datalibrary.common.Null;
import com.osframework.datalibrary.common.SQLResult;
import com.osframework.datalibrary.common.UpdateResult;
import com.osframework.ejb.reference.common.IReferenceMap;
import com.osframework.ejb.reference.security.ISecurity;
import com.osframework.framework.exceptions.NullArgumentException;
import com.osframework.framework.logging.Debug;
import com.osframework.modellibrary.common.ServiceCall;
import com.osframework.modellibrary.reference.group.RecordTypeFramework;
import com.osframework.modellibrary.reference.group.TableNameFramework;
import com.osframework.modellibrary.reference.security.ApplicationUserList;
import com.osframework.modellibrary.reference.security.ApplicationUserModel;

/**
 * The User model is a domain object which stores the system application users
 * The user id is used throughout all tables following the convention <field>_user_id
 * e.g. create_user_id
 * The UserDataModel is auto generated by generator.GenerateModel.getModelSource()
 * and is subclassed by UserModel generated once by GenerateModel.getExtendedModelSouce().
 * Any business logic should be added to UserModel.  The UserList is a collection
 * of UserModels and is auto generated by GenerateModel.getListSource.  How the list stores
 * the models depends on the parameters defined in osrmt_schem.mdb ModelLibrary.
*/
public class ApplicationUserDbAdapter extends BaseAdapter {
	

	private IReferenceMap reference;
	private ISecurity security;

	public ApplicationUserDbAdapter(IReferenceMap reference, ISecurity security) {
		this.reference = reference;
		this.security = security;
	}


	public UpdateResult UpdateApplicationUser(ApplicationUserModel m, ServiceCall call) throws DataUpdateException {
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
			return UpdateApplicationUser(m, call, conn);
		} catch (Exception ex) {
			throw new DataUpdateException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	}


	public UpdateResult UpdateApplicationUser(ApplicationUserModel m, ServiceCall call, DbConnection conn) throws DataUpdateException {
		ApplicationUserModel original = null;
		try {
			if (m == null) {
				throw new NullArgumentException();
			}
			if (m.isNew()) {
				m.setCreateUserId(call.getUserId());
				m.setCreateDt(new GregorianCalendar());
			}
			if (m.hasModified()) {
				original = getApplicationUser(m.getUserId(), conn);
				m.setUpdateDt(new GregorianCalendar());
				m.setUpdateUserId(call.getUserId());
				m.setUpdateCount(original.getUpdateCount()+1);
				m.setSystemAssignedVersionNbr(1);
				m.copyModifiedTo(original);
				UpdateResult result = save(original, conn);
				m.setUserId(original.getUserId());
				return result;
			} else {
				return new UpdateResult();
			}
		} catch (Exception ex) {
			if (original != null) {
				Debug.LogException(this, ex, original.toString());
			} else {
				Debug.LogException(this, ex);
			}
			throw new DataUpdateException(ex); 
		}
	}
	
	private UpdateResult save(ApplicationUserModel m, DbConnection conn) throws SQLException, AccessDataTypeException {
		int nbrRows = 0;
		String sql = "";
		SQLResult result = null;
		Vector params = null;
		try {
			if (m.getUserId()==0) {
				m.setUserId(Db.getNextSequence(TableNameFramework.APPLICATIONUSER, conn));
				sql = getInsertSql();
				params = getInsertParameters(m);
				result = Db.getAccess().executeUpdate(getInsertSql(), getInsertParameters(m), conn);
				nbrRows = result.getRowsUpdated();
			} else {
				sql = getUpdateSql();
				params = getInsertParameters(m);
				result = Db.getAccess().executeUpdate(getUpdateSql(), getUpdateParameters(m), conn);
				nbrRows = result.getRowsUpdated();
			}
			return new UpdateResult(nbrRows,m.getUserId());
		} catch (SQLException ex) {
			Debug.LogError(ex.getMessage(), Db.getFormattedException(ex, sql, params));
			throw ex;
		}
	}
		
	protected int ImportApplicationUser(ApplicationUserModel m) throws SQLException, AccessDataTypeException {
		int nbrRows = 0;
		String sql = "";
		SQLResult result = null;
		Vector params = null;
		try {
			sql = getInsertSql();
			params = getInsertParameters(m);
			result = Db.getAccess().executeUpdate(getInsertSql(), getInsertParameters(m));
			nbrRows = result.getRowsUpdated();
			return nbrRows;
		} catch (SQLException ex) {
			Debug.LogError(ex.getMessage(), Db.getFormattedException(ex, sql, params));
			throw ex;
		}
	}
		
	public int DeleteApplicationUser(ApplicationUserModel m, DbConnection conn) throws DataUpdateException {
		SQLResult result = null;
		try {
			int nbrRows = 0;
			result = Db.getAccess().executeUpdate(getDeleteSql(), getDeleteParameters(m), conn);
			nbrRows = result.getRowsUpdated();
			return nbrRows;
		} catch (Exception ex) {
			Debug.LogException(this, ex);
			throw new DataUpdateException(ex);
		}
	}
	/**
	 * Maps the resultset to the model.
	 */
	public void mapApplicationUser(ResultSet rset, ApplicationUserModel m) throws SQLException {
		if (columnExists(rset, "user_id")) {
			m.setUserId(rset.getInt("user_id"));
			if (rset.wasNull()) m.setUserId(0);
		}
		if (columnExists(rset, "first_name")) {
			m.setFirstName(rset.getString("first_name"));
			if (rset.wasNull()) m.setFirstName(null);
		}
		if (columnExists(rset, "last_name")) {
			m.setLastName(rset.getString("last_name"));
			if (rset.wasNull()) m.setLastName(null);
		}
		if (columnExists(rset, "display_name")) {
			m.setDisplayName(rset.getString("display_name"));
			if (rset.wasNull()) m.setDisplayName(null);
		}
		if (columnExists(rset, "user_login")) {
			m.setUserLogin(rset.getString("user_login"));
			if (rset.wasNull()) m.setUserLogin(null);
		}
		if (columnExists(rset, "password")) {
			m.setPassword(rset.getString("password"));
			if (rset.wasNull()) m.setPassword(null);
		}
		if (columnExists(rset, "password_reset_ind")) {
			m.setPasswordResetInd(rset.getInt("password_reset_ind"));
			if (rset.wasNull()) m.setPasswordResetInd(0);
		}
		if (columnExists(rset, "email")) {
			m.setEmail(rset.getString("email"));
			if (rset.wasNull()) m.setEmail(null);
		}
		if (columnExists(rset, "position_ref_id")) {
			m.setPositionRefId(rset.getInt("position_ref_id"));
			if (rset.wasNull()) m.setPositionRefId(0);
		}
		if (columnExists(rset, "create_dt")) {
			m.setCreateDt(Db.getCalendarDate(rset.getTimestamp("create_dt")));
			if (rset.wasNull()) m.setCreateDt(null);
		}
		if (columnExists(rset, "create_user_id")) {
			m.setCreateUserId(rset.getInt("create_user_id"));
			if (rset.wasNull()) m.setCreateUserId(0);
		}
		if (columnExists(rset, "update_dt")) {
			m.setUpdateDt(Db.getCalendarDate(rset.getTimestamp("update_dt")));
			if (rset.wasNull()) m.setUpdateDt(null);
		}
		if (columnExists(rset, "update_user_id")) {
			m.setUpdateUserId(rset.getInt("update_user_id"));
			if (rset.wasNull()) m.setUpdateUserId(0);
		}
		if (columnExists(rset, "update_count")) {
			m.setUpdateCount(rset.getInt("update_count"));
			if (rset.wasNull()) m.setUpdateCount(0);
		}
		if (columnExists(rset, "active_ind")) {
			m.setActiveInd(rset.getInt("active_ind"));
			if (rset.wasNull()) m.setActiveInd(0);
		}
		if (columnExists(rset, "system_assigned_version_nbr")) {
			m.setSystemAssignedVersionNbr(rset.getInt("system_assigned_version_nbr"));
			if (rset.wasNull()) m.setSystemAssignedVersionNbr(0);
		}
		if (columnExists(rset, "record_type_ref_id")) {
			m.setRecordTypeRefId(rset.getInt("record_type_ref_id"));
			if (rset.wasNull()) m.setRecordTypeRefId(0);
		}
		m.resetModified();
	}

 /**
  * Execute the SQL and return a list for the result set
  */
	public ApplicationUserList  getApplicationUser(String sql) throws DataAccessException {
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
			return getApplicationUser(sql, conn);
		} catch (Exception ex) {
			throw new DataAccessException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	} /**
  * Execute the SQL and return a list for the result set
  */
	public ApplicationUserList  getApplicationUser(String sql, DbConnection conn) throws DataAccessException {
		SQLResult result = null;
		try {
			ApplicationUserList list = new ApplicationUserList();
			result = Db.getAccess().executeQuery(sql, conn);
			ResultSet rset = result.getRset();
			while (rset.next()) {
				ApplicationUserModel m = new ApplicationUserModel();
				mapApplicationUser(rset, m);
				list.add(m);
			}
			list.setReferenceDisplay(reference, security);
			return list;
		} catch (SQLException se) {
			Debug.LogError(this, Db.getFormattedException(se, sql));
			throw new DataAccessException(se);
		} finally {
			try { if (result!=null) result.closeStatements();} catch (Exception ex) {}
		}
	}

 /**
  * Execute the SQL and return a list for the result set
  */
	public ApplicationUserList  getApplicationUser(String sql, Vector params) throws DataAccessException {
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
		return getApplicationUser(sql, params, conn);
		} catch (Exception ex) {
			throw new DataAccessException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	}

 /**
  * Execute the SQL and return a list for the result set
  */
	public ApplicationUserList  getApplicationUser(String sql, Vector params, DbConnection conn) throws DataAccessException {
		SQLResult result = null;
		try {
			ApplicationUserList list = new ApplicationUserList();
			result = Db.getAccess().executeQuery(sql, params, conn);
			ResultSet rset = result.getRset();
			while (rset.next()) {
				ApplicationUserModel m = new ApplicationUserModel();
				mapApplicationUser(rset, m);
				list.add(m);
			}
			list.setReferenceDisplay(reference, security);
			return list;
		} catch (SQLException se) {
			Debug.LogError(this, Db.getFormattedException(se, sql, params));
			throw new DataAccessException(se);
		} catch (AccessDataTypeException ae) {
			throw new DataAccessException(ae);
		} finally {
			try { if (result!=null) result.closeStatements();} catch (Exception ex) {}
		}
	}

	/**
	 * Returns the model from the database.
	 * Returns an empty model if the id is 0 or not found
	 */
	public ApplicationUserModel getApplicationUser(int id) throws DataAccessException { 
		DbConnection conn = null;
		try {
			conn = Db.getConnection();
			return getApplicationUser(id, conn);
		} catch (Exception ex) {
			throw new DataAccessException(ex);
		} finally {
			if (conn != null) {
				conn.close();
			}
		}
	}

	/**
	 * Returns the model from the database.
	 * Returns an empty model if the id is 0 or not found
	 */
	public ApplicationUserModel getApplicationUser(int id, DbConnection conn) throws DataAccessException { 
		SQLResult result = null;
		try {
			ApplicationUserModel m = new ApplicationUserModel();
			// TODO This fails if you actually wanted to get the zero row
			if (id > 0) {
				result = Db.getAccess().executeQuery(getSelectSql(), Db.getParameter(id), conn);
				ResultSet rset = result.getRset();
				if (rset.next()) {
					mapApplicationUser(rset, m);
					m.resetModified();
				}
			}
			return m;
		} catch (Exception ex) {
			Debug.LogException(this, ex, "ApplicationUserModel" + id);
			throw new DataAccessException(ex);
		} finally {
			try { if (result!=null) result.closeStatements();} catch (Exception ex) {}
		}
	}

	public ApplicationUserList exportApplicationUser() throws DataAccessException {
		int rows = Db.countTable("application_user");
		Debug.LogInfo(this, rows + " found in application_user");
		String sql = "select * from application_user where record_type_ref_id in (?, ?)";
		ApplicationUserList list = this.getApplicationUser(sql, Db.getParameter(RecordTypeFramework.SYSTEMREFERENCE, RecordTypeFramework.USERREFERENCE)); 
		Debug.LogInfo(this,list.size()  + " application_user rows exported");
		return list;
	}

	public int importApplicationUser(ApplicationUserList list) throws Exception {
		Enumeration e1 = list.elements();
		int rows = 0;
		while (e1.hasMoreElements()) {
			ApplicationUserModel m = (ApplicationUserModel) e1.nextElement();
			rows += ImportApplicationUser(m);
		}
		Debug.LogInfo(this, rows + " reference_group rows imported");
		return rows;
	}

	private String getSelectSql() {
		return "select user_id, first_name, last_name, display_name, "
			+ "user_login, password, password_reset_ind, email, "
			+ "position_ref_id, create_dt, create_user_id, update_dt, "
			+ "update_user_id, update_count, active_ind, system_assigned_version_nbr, "
			+ "record_type_ref_id"
			+ " from application_user "
			+ " where user_id = ?";				 
	}
	
	private String getInsertSql() {
		return "insert into application_user (user_id, first_name, last_name, display_name, "
			+ "user_login, password, password_reset_ind, email, "
			+ "position_ref_id, create_dt, create_user_id, update_dt, "
			+ "update_user_id, update_count, active_ind, system_assigned_version_nbr, "
			+ "record_type_ref_id)"
			+ " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";				 
	}
	
	private Vector getInsertParameters(ApplicationUserModel m) {
		Vector v = new Vector(17);
		v.add(new Integer(m.getUserId()));
		if (m.getFirstName() != null) v.add(m.getFirstName());
		else v.add(new Null(new String()));
		if (m.getLastName() != null) v.add(m.getLastName());
		else v.add(new Null(new String()));
		if (m.getDisplayName() != null) v.add(m.getDisplayName());
		else v.add(new Null(new String()));
		if (m.getUserLogin() != null) v.add(m.getUserLogin());
		else v.add(new Null(new String()));
		if (m.getPassword() != null) v.add(m.getPassword());
		else v.add(new Null(new String()));
		v.add(new Integer(m.getPasswordResetInd()));
		if (m.getEmail() != null) v.add(m.getEmail());
		else v.add(new Null(new String()));
		v.add(new Integer(m.getPositionRefId()));
		if (m.getCreateDt() != null) v.add(m.getCreateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getCreateUserId()));
		if (m.getUpdateDt() != null) v.add(m.getUpdateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getUpdateUserId()));
		v.add(new Integer(m.getUpdateCount()));
		v.add(new Integer(m.getActiveInd()));
		v.add(new Integer(m.getSystemAssignedVersionNbr()));
		v.add(new Integer(m.getRecordTypeRefId()));
		return v;
	}
	
	private String getUpdateSql() {
		return "update application_user set  first_name = ?, last_name = ?, display_name = ?, "
			+ "user_login = ?, password = ?, password_reset_ind = ?, email = ?, "
			+ "position_ref_id = ?, create_dt = ?, create_user_id = ?, update_dt = ?, "
			+ "update_user_id = ?, update_count = ?, active_ind = ?, system_assigned_version_nbr = ?, "
			+ "record_type_ref_id = ? "
			+ " where user_id = ?";				 
	}
	
	private Vector getUpdateParameters(ApplicationUserModel m) {
		Vector v = new Vector(17);
		if (m.getFirstName() != null) v.add(m.getFirstName());
		else v.add(new Null(new String()));
		if (m.getLastName() != null) v.add(m.getLastName());
		else v.add(new Null(new String()));
		if (m.getDisplayName() != null) v.add(m.getDisplayName());
		else v.add(new Null(new String()));
		if (m.getUserLogin() != null) v.add(m.getUserLogin());
		else v.add(new Null(new String()));
		if (m.getPassword() != null) v.add(m.getPassword());
		else v.add(new Null(new String()));
		v.add(new Integer(m.getPasswordResetInd()));
		if (m.getEmail() != null) v.add(m.getEmail());
		else v.add(new Null(new String()));
		v.add(new Integer(m.getPositionRefId()));
		if (m.getCreateDt() != null) v.add(m.getCreateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getCreateUserId()));
		if (m.getUpdateDt() != null) v.add(m.getUpdateDt());
		else v.add(new Null(new GregorianCalendar()));
		v.add(new Integer(m.getUpdateUserId()));
		v.add(new Integer(m.getUpdateCount()));
		v.add(new Integer(m.getActiveInd()));
		v.add(new Integer(m.getSystemAssignedVersionNbr()));
		v.add(new Integer(m.getRecordTypeRefId()));
		v.add(new Integer(m.getUserId()));
		return v;
	}

	private Vector getDeleteParameters(ApplicationUserModel m) {
		Vector v = new Vector(17);
		v.add(new Integer(m.getUserId()));
		return v;
	}

	private String getDeleteSql() {
		return "delete from application_user where user_id = ?";				 
	}

}
